### ISSUE TITLE
Training from scratch failed by setting issolo=True in yolov6n_seg.py 

### ISSUE THREAD

**Issue by DrChungAlbert** [meituan/YOLOv6#1007]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I want to train the yolov6n-seg by turning on the issolo in yolov6n_seg.py :

# YOLOv6n-seg model
model = dict(
    type='YOLOv6n',
    pretrained=None,
    depth_multiple=0.33,
    width_multiple=0.25,
    backbone=dict(
        type='EfficientRep',
        num_repeats=[1, 6, 12, 18, 6],
        out_channels=[64, 128, 256, 512, 1024],
        fuse_P2=True,
        cspsppf=True,
        ),
    neck=dict(
        type='RepBiFPANNeck',
        num_repeats=[12, 12, 12, 12],
        out_channels=[256, 128, 128, 256, 256, 512],
        ),
    head=dict(
        type='EffiDeHead',
        in_channels=[128, 256, 512],
        num_layers=3,
        begin_indices=24,
        npr=256,
        nm=32,
        isseg=True,
        issolo=True,      <=== Turn on this one
        anchors=3,
        anchors_init=[[10,13, 19,19, 33,23],
                      [30,61, 59,59, 59,119],
                      [116,90, 185,185, 373,326]],
        out_indices=[17, 20, 23],
        strides=[8, 16, 32],
        atss_warmup_epoch=0,
        iou_type='siou',
        use_dfl=False, # set to True if you want to further train with distillation
        reg_max=0, # set to 16 if you want to further train with distillation
        distill_weight={
            'class': 1.0,
            'dfl': 1.0,
        },
    )
)

solver = dict(
    optim='SGD',
    lr_scheduler='Cosine',
    lr0=0.02,
    lrf=0.01,
    momentum=0.937,
    weight_decay=0.001,
    warmup_epochs=3.0,
    warmup_momentum=0.8,
    warmup_bias_lr=0.1
)

data_aug = dict(
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    degrees=0.0,
    translate=0.1,
    scale=0.5,
    shear=0.0,
    flipud=0.0,
    fliplr=0.5,
    mosaic=1.0,
    mixup=0.0,
)

Training the YOLOV6n-seg from scratch by command below:
CUDA_VISIBLE_DEVICES=5,6,7 python -m torch.distributed.launch --nproc_per_node=3 tools/train.py --conf configs/yolov6n_seg.py --img-size 512 --batch 64 --workers 8 --device 5,6,7 --save_ckpt_on_last_n_epoch=10

But after 19 epoches got the error message:
Epoch        lr  iou_loss  dfl_loss  cls_loss  seg_loss
   19/399    0.05333    0.4443         0    0.8794     0.474: 100%|██████████| 1112/1112 [04:54<00:
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main(args)
  File "tools/train.py", line 132, in main
    trainer.train()
  File "/data1//YOLOv6-seg_test/yolov6/core/engine.py", line 125, in train
    self.after_epoch()
  File "/data1//YOLOv6-seg_test/yolov6/core/engine.py", line 200, in after_epoch
    self.eval_model()
  File "/data1//YOLOv6-seg_test/yolov6/core/engine.py", line 236, in eval_model
    results, vis_outputs, vis_paths = eval.run(self.data_dict,
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data1/YOLOv6-seg_test/tools/eval.py", line 155, in run
    model = val.init_model(model, weights, task)
  File "/data1/YOLOv6-seg_test/yolov6/core/evaler.py", line 85, in init_model
    model(torch.zeros(1, 3, self.img_size, self.img_size).to(self.device).type_as(next(model.parameters())))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data1/YOLOv6-seg_test/yolov6/models/yolo.py", line 40, in forward
    x = self.detect(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data1/YOLOv6-seg_test/yolov6/models/heads/effidehead_fuseab_seg_solo.py", line 265, in forward
    seg_conf_list_af.append(torch.cat([proto_no, seg_output_af.reshape([b, 67, l])], axis = 1)) #[which_proto, (32...)]
RuntimeError: shape '[1, 67, 4096]' is invalid for input of size 143360
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 67646 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 67647 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 67645) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 770, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

### Additional
size 143360 = [1,35,4096] ，proto_list: [(bs, 32, w, h), ...]
_No response_

**Comment by Chilicyy** [comment]
Hi @DrChungAlbert , the config files in [this folder](https://github.com/meituan/YOLOv6/tree/yolov6-seg/configs/exp) should be used if you want to train segmentation models with SOLO head.
