### ISSUE TITLE
model.names in evaler.py

### ISSUE THREAD

**Issue by linghusmile** [meituan/YOLOv6#1024]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

当我拉取了最新的yolov6 想跑官方测试案例coco数据集后 ，出现了以下报错，从代码来看 model确实没有 model.names 属性，以及 model.nc 按照其他帖子中给的方式写成了固定值，nc，以及names 应该都是yaml中配置的内容 应该不是模型的属性吧？ 运行官方测试案例出现如下崩溃：
Traceback (most recent call last):
  File "tools/eval.py", line 173, in <module>
    main(args)
  File "tools/eval.py", line 168, in main
    run(**vars(args))
  File "/home/****/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "tools/eval.py", line 163, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/home/****/git_ebooks/YOLOv6/yolov6/core/evaler.py", line 321, in eval_model
    LOGGER.info(pf % (model.names[nc_i], len(label_count_dicts[nc_i]["images"]), label_count_dicts[nc_i]["anns"], p[i], r[i], f1[i], map50, map))
  File "/home/****/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Model' object has no attribute 'names'

**Comment by Chilicyy** [comment]
@linghusmile 您好，麻烦提供下启动命令，谢谢。

**Comment by kaikaizhu** [comment]
@Chilicyy 
我遇到了同样的问题：
测试coco数据集上每个类别的map时，在命令中加入--verbose，就会出现 'Model' object has no attribute 'names' 和 'Model' object has no attribute 'nc' 的报错。
执行命令是：python tools/eval.py --data data/coco.yaml --batch 2 --weights weights/yolov6n.pt --task val --reproduce_640_eval --verbose

**Comment by kaikaizhu** [comment]
我知道应该怎么修改了。
把 model.nc 改为 self.data['nc']
把 model.names 改为 self.data['names']
