### ISSUE TITLE
Issue with YOLOv6 Segmentation Model Using Polygon Labels

### ISSUE THREAD

**Issue by hamedgorji** [meituan/YOLOv6#1051]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Dear YOLOv6 Team,

I am encountering an issue with the YOLOv6 segmentation model when using polygon labels. I organized my data directory according to your guidelines for custom datasets. 

```
custom_dataset
├── images
│   ├── train
│   │   ├── train0.jpg
│   │   └── train1.jpg
│   ├── val
│   │   ├── val0.jpg
│   │   └── val1.jpg
│   └── test
│       ├── test0.jpg
│       └── test1.jpg
└── labels
    ├── train
    │   ├── train0.txt
    │   └── train1.txt
    ├── val
    │   ├── val0.txt
    │   └── val1.txt
    └── test
        ├── test0.txt
        └── test1.txt
```

The label format I used is polygon in YOLO format. 
```
1 0.654297 0.177083 0.637695 0.177083 0.631836 0.180990 0.621094 0.203125 0.623047 0.223958 0.628906 0.225260 0.625000 0.238281 0.625977 0.240885 0.632812 0.244792 0.652344 0.242188 0.665039 0.230469 0.671875 0.213542 0.666992 0.188802
0 0.840820 0.912760 0.832031 0.907552 0.812500 0.921875 0.799805 0.945312 0.792969 0.929688 0.777344 0.949219 0.781250 0.968750 0.791992 0.998698 0.798828 0.998698 0.801758 0.985677 0.808594 0.988281
```

However, I receive the following error when training the model:

```
img record information path is: C:\Users\Hamed\YOLOv6-seg\data\images\.train_cache.json
Train: Final numbers of valid images: 20155/ labels: 20155.
Traceback (most recent call last):
  File "C:\Users\Hamed\YOLOv6-seg\tools\train.py", line 142, in <module>
    main(args)
  File "C:\Users\Hamed\YOLOv6-seg\tools\train.py", line 127, in main
    trainer = Trainer(args, cfg, device)
  File "C:\Users\Hamed\YOLOv6-seg\yolov6\core\engine.py", line 94, in __init__
    self.train_loader, self.val_loader = self.get_data_loader(self.args, self.cfg, self.data_dict)
  File "C:\Users\Hamed\YOLOv6-seg\yolov6\core\engine.py", line 406, in get_data_loader
    train_loader = create_dataloader(train_path, args.img_size, args.batch_size // args.world_size, grid_size,
  File "C:\Users\Hamed\YOLOv6-seg\yolov6\data\data_load.py", line 46, in create_dataloader
    dataset = TrainValDataset(
  File "C:\Users\Hamed\YOLOv6-seg\yolov6\data\seg_datasets.py", line 87, in __init__
    self.labels, self.segments = self.get_segment(self.labels)
  File "C:\Users\Hamed\YOLOv6-seg\yolov6\data\seg_datasets.py", line 297, in get_segment
    z1.append(np.asarray(l[:5]).reshape(1, 5).astype(np.float32))
ValueError: cannot reshape array of size 3 into shape (1,5)
```
Surprisingly, the model works when I provide labels in the bounding box format, but the segmentation model output after training is in bounding boxes as expected. However, I need polygons for segmentation.

Could you please help me resolve this issue so that the model can correctly process polygon labels for segmentation?

Thanks

### Additional
```
python tools/train.py --batch 8 --epochs 50 --conf configs/yolov6n_seg.py --data data/data.yaml --img-size 480 --device 0

```

**Comment by hamedgorji** [comment]
Update: I found the issue. Some of my annotations had a problem and instead of polygons, they just contained 3 numbers.
