### ISSUE TITLE
COCOEval Error

### ISSUE THREAD

**Issue by defrag-bambino** [meituan/YOLOv6#151]
Hi,

I tried running the training on a custom dataset. The dataset is in the yolov5 format, so basically a /images and /labels folder. For now, I ran it using the same folder for test and validation, just to see if training works at all. Sadly, a big chunk of my images are "corrupted" for some reason, which they are not if I run the same dataset through yolov5's training.

After the first episode finishes, I get this error:

`
Evaluating speed.

Evaluating mAP by pycocotools.
Saving ./runs/train/exp/predictions.json...
loading annotations into memory...
Done (t=0.59s)
creating index...
index created!
Loading and preparing results...
DONE (t=16.06s)
creating index...
index created!
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.

Training completed in 1.587 hours.
Traceback (most recent call last):
  File "tools/train.py", line 90, in <module>
    main(args)
  File "tools/train.py", line 80, in main
    trainer.train()
  File "/mnt/mylocal/YOLOv6/yolov6/core/engine.py", line 62, in train
    self.train_in_loop()
  File "/mnt/mylocal/YOLOv6/yolov6/core/engine.py", line 81, in train_in_loop
    self.eval_and_save()
  File "/mnt/mylocal/YOLOv6/yolov6/core/engine.py", line 107, in eval_and_save
    self.eval_model()
  File "/mnt/mylocal/YOLOv6/yolov6/core/engine.py", line 126, in eval_model
    results = eval.run(self.data_dict,
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/mylocal/YOLOv6/tools/eval.py", line 76, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/mnt/mylocal/YOLOv6/yolov6/core/evaler.py", line 130, in eval_model
    cocoEval = COCOeval(anno, pred, 'bbox')
  File "/opt/conda/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 84, in __init__
    self.params.imgIds = sorted(cocoGt.getImgIds())
TypeError: '<' not supported between instances of 'str' and 'int'
`

**Comment by DongLizhong** [comment]
I meet same problem when i train my dataset.  Seems it's not allow any letter in the image name?

**Comment by fanweiya** [comment]
I have same error

**Comment by DongLizhong** [comment]
I try to modify the cocoeval.py, and it worked.
'
if not cocoGt is None:
    # self.params.imgIds = sorted(cocoGt.getImgIds())
    # self.params.catIds = sorted(cocoGt.getCatIds())
    self.params.imgIds = cocoGt.getImgIds()
    self.params.catIds = cocoGt.getCatIds()
'

**Comment by HeZhang33** [comment]
Same problem here!

ERROR in evaluate and save model.
ERROR in training loop or eval/save model.

Training completed in 0.074 hours.
Traceback (most recent call last):
  File "tools/train.py", line 92, in <module>
    main(args)
  File "tools/train.py", line 82, in main
    trainer.train()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/engine.py", line 70, in train
    self.train_in_loop()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/engine.py", line 89, in train_in_loop
    self.eval_and_save()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/engine.py", line 115, in eval_and_save
    self.eval_model()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/engine.py", line 134, in eval_model
    results = eval.run(self.data_dict,
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/tools/eval.py", line 80, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/evaler.py", line 128, in eval_model
    cocoEval = COCOeval(anno, pred, 'bbox')
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 5, in linspace
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/numpy/core/function_base.py", line 113, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by wenjunx** [comment]
> Same problem here!
> 
> ERROR in evaluate and save model. ERROR in training loop or eval/save model.
> 
> Training completed in 0.074 hours. Traceback (most recent call last): File "tools/train.py", line 92, in main(args) File "tools/train.py", line 82, in main trainer.train() File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/engine.py", line 70, in train self.train_in_loop() File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/engine.py", line 89, in train_in_loop self.eval_and_save() File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/engine.py", line 115, in eval_and_save self.eval_model() File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/engine.py", line 134, in eval_model results = eval.run(self.data_dict, File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/tools/eval.py", line 80, in run eval_result = val.eval_model(pred_result, model, dataloader, task) File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/evaler.py", line 128, in eval_model cocoEval = COCOeval(anno, pred, 'bbox') File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 76, in **init** self.params = Params(iouType=iouType) # parameters File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 527, in **init** self.setDetParams() File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True) File "<**array_function** internals>", line 5, in linspace File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/numpy/core/function_base.py", line 113, in linspace num = operator.index(num) TypeError: 'numpy.float64' object cannot be interpreted as an integer

解决了吗？我用最新的代码也是这个错误
