### ISSUE TITLE
dump_all() got an unexpected keyword argument 'sort_keys'

### ISSUE THREAD

**Issue by Shrabana97** [meituan/YOLOv6#194]
I am using below line for training:
!python /content/drive/MyDrive/object_detection_yolov6/YOLOv6/tools/train.py --batch 32 --conf /content/drive/MyDrive/object_detection_yolov6/YOLOv6/configs/yolov6s_finetune.py --data /content/YOLOv6/data/dataset.yaml --device 0

but it's throwing error. 

Using 1 GPU for training... 
Traceback (most recent call last):
  File "/content/drive/MyDrive/object_detection_yolov6/YOLOv6/tools/train.py", line 92, in <module>
    main(args)
  File "/content/drive/MyDrive/object_detection_yolov6/YOLOv6/tools/train.py", line 71, in main
    cfg, device = check_and_init(args)
  File "/content/drive/MyDrive/object_detection_yolov6/YOLOv6/tools/train.py", line 61, in check_and_init
    save_yaml(vars(args), osp.join(args.save_dir, 'args.yaml'))
  File "/content/drive/MyDrive/object_detection_yolov6/YOLOv6/yolov6/utils/events.py", line 30, in save_yaml
    yaml.safe_dump(data_dict, f, sort_keys=False)
  File "/usr/local/lib/python3.7/dist-packages/yaml/__init__.py", line 216, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'

**Comment by 4ff4n** [comment]
@Shrabana97 for me  this issue was resolved by installing PyYAML>=5.3.1
