### ISSUE TITLE
Error when finetuning self-defined dataset: Results do not correspond to current coco set

### ISSUE THREAD

**Issue by fireoil** [meituan/YOLOv6#207]
Evaluating speed.

Evaluating mAP by pycocotools.
Saving ./runs/train/exp/predictions.json...
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.

Training completed in 0.002 hours.
Traceback (most recent call last):
  File "tools/train.py", line 87, in <module>
    main(args)
  File "tools/train.py", line 77, in main
    trainer.train()
  File "/zhangxin/training/YOLOv6/yolov6/core/engine.py", line 62, in train
    self.train_in_loop()
  File "/zhangxin/training/YOLOv6/yolov6/core/engine.py", line 81, in train_in_loop
    self.eval_and_save()
  File "/zhangxin/training/YOLOv6/yolov6/core/engine.py", line 107, in eval_and_save
    self.eval_model()
  File "/zhangxin/training/YOLOv6/yolov6/core/engine.py", line 132, in eval_model
    task='train')
  File "/root/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/zhangxin/training/YOLOv6/tools/eval.py", line 76, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/zhangxin/training/YOLOv6/yolov6/core/evaler.py", line 129, in eval_model
    pred = anno.loadRes(pred_json)
  File "/root/anaconda3/lib/python3.7/site-packages/pycocotools/coco.py", line 328, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

**Comment by mtjhl** [comment]
Hi， did you set `is_coco` to False [here](
https://github.com/meituan/YOLOv6/blob/41817654a1125103c4163b17b046b8dbb47cb196/data/coco.yaml#L9)

**Comment by jcrdeep** [comment]
In my case, it was giving the default file name for the JSON file, i.e: `instances_val2017.json` and also by giving `is_coco: False`


```
val: coco3/images/val2017
anno_path: coco3/annotations/instances_val2017.json
is_coco: False
```

**Comment by mtjhl** [comment]
@fireoil Does your problem solved? If you still have same proble, please tell us.
