### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'Warning'

### ISSUE THREAD

**Issue by lukazso** [meituan/YOLOv6#215]
I accidentally ran the inference with a corrupted image. This triggered the exception here:

https://github.com/meituan/YOLOv6/blob/af897f2aff07c7f46c97875e3657eb1968f1e1a1/yolov6/core/inferer.py#L101-L105

This triggered a further error:
```
Traceback (most recent call last):
  File "tools/infer.py", line 108, in <module>
    main(args)
  File "tools/infer.py", line 103, in main
    run(**vars(args))
  File "/home/lukas/Development/pycharm_workspace/YOLOv6/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "tools/infer.py", line 96, in run
    inferer.infer(conf_thres, iou_thres, classes, agnostic_nms, max_det, save_dir, save_txt, save_img, hide_labels, hide_conf)
  File "/home/lukas/Development/pycharm_workspace/YOLOv6/yolov6/core/inferer.py", line 58, in infer
    img, img_src = self.precess_image(img_path, self.img_size, self.stride, self.half)
  File "/home/lukas/Development/pycharm_workspace/YOLOv6/yolov6/core/inferer.py", line 105, in precess_image
    LOGGER.Warning(e)
AttributeError: 'Logger' object has no attribute 'Warning'
```

I think there is a typo and in line 105 `LOGGER.Warning` should actually be `LOGGER.warning`. I tested it and this little fix mitigates the error. I will create a quick PR for this.

OS: Ubuntu 20.04
Python Version: Python 3.8.10
All requirements as stated in `requirements.txt`

**Comment by mtjhl** [comment]
Sorry for the inconvenience, we have fix the mistake in spell of `LOGGER.Warning` to `LOGGER.warning`, please run `git pull ` to update the code.
