### ISSUE TITLE
AssertionError: ../data/images/train is an invalid directory path!

### ISSUE THREAD

**Issue by cyrax7** [meituan/YOLOv6#245]
Using 1 GPU for training... 
training args are: Namespace(batch_size=16, check_images=False, check_labels=False, conf_file='configs/yolov6s_finetune.py', data_path='dataset101.yaml', device='0', dist_url='env://', epochs=10, eval_final_only=False, eval_interval=2, gpu_count=0, heavy_eval_range=50, img_size=640, local_rank=-1, name='exp', output_dir='./runs/train', rank=-1, resume=False, save_dir='runs/train/exp7', workers=8, world_size=1)

Traceback (most recent call last):
  File "tools/train.py", line 112, in <module>
    main(args)
  File "tools/train.py", line 101, in main
    trainer = Trainer(args, cfg, device)
  File "/content/drive/MyDrive/YoloV6_training test/YOLOv6/yolov6/core/engine.py", line 42, in __init__
    self.train_loader, self.val_loader = self.get_data_loader(args, cfg, self.data_dict)
  File "/content/drive/MyDrive/YoloV6_training test/YOLOv6/yolov6/core/engine.py", line 222, in get_data_loader
    check_labels=args.check_labels, data_dict=data_dict, task='train')[0]
  File "/content/drive/MyDrive/YoloV6_training test/YOLOv6/yolov6/data/data_load.py", line 54, in create_dataloader
    task=task,
  File "/content/drive/MyDrive/YoloV6_training test/YOLOv6/yolov6/data/datasets.py", line 63, in __init__
    self.img_paths, self.labels = self.get_imgs_labels(self.img_dir)
  File "/content/drive/MyDrive/YoloV6_training test/YOLOv6/yolov6/data/datasets.py", line 201, in get_imgs_labels
    assert osp.exists(img_dir), f"{img_dir} is an invalid directory path!"
AssertionError: ../data/images/train is an invalid directory path!

**Comment by ShisuiUzumaki** [comment]
Are you executing train.py from terminal or IDE run tool?

If it is from run tool you will need to provide absolute paths in data.yaml, train.py argparse and yolov6 config file

**Comment by MTChengMeng** [comment]
Hi, we suggest you check the directory of your dataset according to [tutorials](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md#1-prepare-your-own-dataset) and run the code again.
If it doesn't work, you can provide your yaml file in ./data and the structure of your dataset directory so we can find out the problem.

**Comment by cyrax7** [comment]
@MTChengMeng @ShisuiUzumaki  thanks for all the help I did find a solution to the problem
