### ISSUE TITLE
CUDA error: invalid device ordinal   -  Multiple GPU issue

### ISSUE THREAD

**Issue by brucemuller** [meituan/YOLOv6#313]
Hi

I'm getting the following error when trying multi GPU: python -m torch.distributed.launch --nproc_per_node 8 tools/train.py --batch 32 --conf configs/yolov6s.py --data data/chess.yaml --device 0,1

It seems the GPU IDs are wrong when using distributed. I've tired using  CUDA_DEVICE_ORDER=PCI_BUS_ID but it did not help.
Any ideas what's going on here?

#######################################

/home/bruce/miniconda3/envs/yolo/lib/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Using 2 GPU for training... 
training args are: Namespace(batch_size=32, check_images=False, check_labels=False, conf_file='configs/yolov6s.py', data_path='data/chess.yaml', device='0,1', dist_url='env://', epochs=400, eval_final_only=False, eval_interval=20, gpu_count=0, heavy_eval_range=50, img_size=640, local_rank=0, name='exp', output_dir='./runs/train', rank=0, resume=False, save_dir='runs/train/exp19', workers=8, world_size=8)

Initializing process group... 
Added key: store_based_barrier_key:1 to store for rank: 0
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 96, in main
    torch.cuda.set_device(args.local_rank)
  File "/home/bruce/miniconda3/envs/yolo/lib/python3.6/site-packages/torch/cuda/__init__.py", line 311, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 96, in main
    torch.cuda.set_device(args.local_rank)
  File "/home/bruce/miniconda3/envs/yolo/lib/python3.6/site-packages/torch/cuda/__init__.py", line 311, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 96, in main
    torch.cuda.set_device(args.local_rank)
  File "/home/bruce/miniconda3/envs/yolo/lib/python3.6/site-packages/torch/cuda/__init__.py", line 311, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 96, in main
    torch.cuda.set_device(args.local_rank)
  File "/home/bruce/miniconda3/envs/yolo/lib/python3.6/site-packages/torch/cuda/__init__.py", line 311, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 96, in main
    torch.cuda.set_device(args.local_rank)
  File "/home/bruce/miniconda3/envs/yolo/lib/python3.6/site-packages/torch/cuda/__init__.py", line 311, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 96, in main
    torch.cuda.set_device(args.local_rank)
  File "/home/bruce/miniconda3/envs/yolo/lib/python3.6/site-packages/torch/cuda/__init__.py", line 311, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal

**Comment by mtjhl** [comment]
You set `--nproc_per_node 8` while set  `--device 1,2`,  it show be `--device 0,1,2,3,4,5,6,7`

**Comment by brucemuller** [comment]
Ah ooops! Thanks!
