### ISSUE TITLE
issue with distributed training 

### ISSUE THREAD

**Issue by elnou** [meituan/YOLOv6#345]
Hi,

I am trying to run the distributed training but getting the following error. 
python3 -m torch.distributed.launch --nproc_per_node 12 tools/train.py --batch 256 --conf configs/yolov6s.py --data data/coco.yaml --device 0,1
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nvidia/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 148, in <module>
    from torch.distributed.run import get_args_parser, run
  File "/home/nvidia/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 382, in <module>
    from torch.distributed.elastic.rendezvous.utils import _parse_rendezvous_config
  File "/home/nvidia/.local/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/__init__.py", line 131, in <module>
    from .api import *  # noqa: F403
  File "/home/nvidia/.local/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/api.py", line 10, in <module>
    from torch.distributed import Store
ImportError: cannot import name 'Store' from 'torch.distributed' (/home/nvidia/.local/lib/python3.8/site-packages/torch/distributed/__init__.py)

Can you please help me with that?

Thank you,

**Comment by mtjhl** [comment]
Hi, you set `--nproc_per_node 12`, if you want to use 2 GPU, it should be 2, not 12.

**Comment by elnou** [comment]
Hi, 
I changed it to 2 but the same issue: It cannot import name 'Store' from torch.distributed

python3 -m torch.distributed.launch --nproc_per_node 2 tools/train.py --batch 256 --conf configs/yolov6s.py --data data/coco.yaml --device 0,1
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nvidia/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 148, in <module>
    from torch.distributed.run import get_args_parser, run
  File "/home/nvidia/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 382, in <module>
    from torch.distributed.elastic.rendezvous.utils import _parse_rendezvous_config
  File "/home/nvidia/.local/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/__init__.py", line 131, in <module>
    from .api import *  # noqa: F403
  File "/home/nvidia/.local/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/api.py", line 10, in <module>
    from torch.distributed import Store
ImportError: cannot import name 'Store' from 'torch.distributed' (/home/nvidia/.local/lib/python3.8/site-packages/torch/distributed/__init__.py)


Can you please help?

Thank you,

**Comment by mtjhl** [comment]
What's your PyTorch version? When you train with single gpu, can it runs normally?

**Comment by elnou** [comment]
Hi,

>>> torch.__version__
'1.12.0a0+84d1cb9.nv22.4'
>>> 

I am running the training on jetson orin and it is working for single GPU.

Thank you

**Comment by mtjhl** [comment]
Is there two version of python in your computer? one in your `/usr`, another in `/home/nvidia/.local`?

**Comment by elnou** [comment]
Hi,

yes it is.
