### ISSUE TITLE
help  AttributeError: module 'tools.eval' has no attribute 'run'

### ISSUE THREAD

**Issue by yuanzhougege** [meituan/YOLOv6#353]
Training completed in 0.053 hours.
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 104, in main
    trainer.train()
  File "/docker_code/yolov6/YOLOv6-main/yolov6/core/engine.py", line 81, in train
    self.train_in_loop()
  File "/docker_code/yolov6/YOLOv6-main/yolov6/core/engine.py", line 100, in train_in_loop
    self.eval_and_save()
  File "/docker_code/yolov6/YOLOv6-main/yolov6/core/engine.py", line 126, in eval_and_save
    self.eval_model()
  File "/docker_code/yolov6/YOLOv6-main/yolov6/core/engine.py", line 145, in eval_model
    results = eval.run(self.data_dict,
AttributeError: module 'tools.eval' has no attribute 'run'

**Comment by yurkovak** [comment]
Try doing this prior to your command:
```shell
export PYTHONPATH=$PYTHONPATH:/docker_code/yolov6/YOLOv6-main/
```

**Comment by mtjhl** [comment]
Have you install YOLOX? try `pip uninstall yolox`, because YOLOX built a library with the name tools.

**Comment by mtjhl** [comment]
You can open python terminal, run
```
from tools import run 
```
If error occurs, see which package does not have `run`, then pip uninstall the package. Currently, I know yolox and detectron2 will cause this problem.

**Comment by lugengyou** [comment]
> Have you install YOLOX? try `pip uninstall yolox`, because YOLOX built a library with the name tools.

I meet the same problem, because I have build YOLOX. If you use anaconda to manage your environment, you can also built a new virtual environment for implementing yolov6 to solve this issue.
