### ISSUE TITLE
TypeError: Object of type Tensor is not JSON serializable 

### ISSUE THREAD

**Issue by yuanzhougege** [meituan/YOLOv6#365]
Training start...

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
  0%|          | 0/267 [00:00<?, ?it/s]                                                                                                                                                /opt/conda/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
     0/399     1.839     1.033     3.927     2.086: 100%|██████████| 267/267 [15:20<00:00,  3.45s/it]                                                                                  
Inferencing model in val datasets.: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 52/52 [00:37<00:00,  1.37it/s]

Evaluating speed.

Evaluating mAP by pycocotools.
Saving runs/train/exp13/predictions.json...
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.

Training completed in 0.268 hours.
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 104, in main
    trainer.train()
  File "/docker_code/yolov6/YOLOv6-main/yolov6/core/engine.py", line 87, in train
    self.train_in_loop()
  File "/docker_code/yolov6/YOLOv6-main/yolov6/core/engine.py", line 106, in train_in_loop
    self.eval_and_save()
  File "/docker_code/yolov6/YOLOv6-main/yolov6/core/engine.py", line 138, in eval_and_save
    self.eval_model()
  File "/docker_code/yolov6/YOLOv6-main/yolov6/core/engine.py", line 242, in eval_model
    results, vis_outputs, vis_paths = eval.run(self.data_dict,
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/docker_code/yolov6/YOLOv6-main/tools/eval.py", line 83, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/docker_code/yolov6/YOLOv6-main/yolov6/core/evaler.py", line 132, in eval_model
    json.dump(pred_results, f)
  File "/opt/conda/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/opt/conda/lib/python3.8/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/opt/conda/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/conda/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/conda/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/opt/conda/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable

训练一轮后报错 为什么

**Comment by mtjhl** [comment]
您有对代码进行修改吗？

**Comment by yuanzhougege** [comment]
> 您有对代码进行修改吗？

仅仅注释了datasets.py里面的 im.verify() 如果不这样的话会报更多的错误，其他的没有修改，用了自定义数据集，怎么回事，求解决

**Comment by mtjhl** [comment]
建议您重新拉一下代码，先用 COCO 数据集训练一个 epoch 测试一下，然后再做相应的修改。如果依然报错，麻烦请告知一下我们。

**Comment by YijiaZhao** [comment]
这个问题解决了吗？我在做敏感度分析的时候也遇到了这个error

**Comment by YijiaZhao** [comment]
需要把json.dump(pred_results, f) 改成 json.dump(pred_results[0], f)
