### ISSUE TITLE
Custom_Dataset_ error - assert osp.exists(label_dir), f"{label_dir} is an invalid directory path!"

### ISSUE THREAD

**Issue by oariasmx** [meituan/YOLOv6#375]
Hello

I try to train with a custom dataset, but having following error

/home/aro2ju/painted-markings-search/yolov6/YOLOv6
Using 1 GPU for training... 
training args are: Namespace(batch_size=32, check_images=False, check_labels=False, conf_file='configs/yolov6s.py', data_path='data/mask.yaml', device='0', dist_url='env://', epochs=20, eval_final_only=False, eval_interval=20, gpu_count=0, heavy_eval_range=50, img_size=416, local_rank=-1, name='exp', output_dir='./runs/train', rank=-1, resume=False, save_dir='runs/train/exp55', workers=8, world_size=1)

Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 103, in main
    trainer = Trainer(args, cfg, device)
  File "/home/aro2ju/painted-markings-search/yolov6/YOLOv6/yolov6/core/engine.py", line 47, in __init__
    self.train_loader, self.val_loader = self.get_data_loader(args, cfg, self.data_dict)
  File "/home/aro2ju/painted-markings-search/yolov6/YOLOv6/yolov6/core/engine.py", line 326, in get_data_loader
    train_loader = create_dataloader(train_path, args.img_size, args.batch_size // args.world_size, grid_size,
  File "/home/aro2ju/painted-markings-search/yolov6/YOLOv6/yolov6/data/data_load.py", line 41, in create_dataloader
    dataset = TrainValDataset(
  File "/home/aro2ju/painted-markings-search/yolov6/YOLOv6/yolov6/data/datasets.py", line 65, in __init__
    self.img_paths, self.labels = self.get_imgs_labels(self.img_dir)
  File "/home/aro2ju/painted-markings-search/yolov6/YOLOv6/yolov6/data/datasets.py", line 258, in get_imgs_labels
    assert osp.exists(label_dir), f"{label_dir} is an invalid directory path!"
AssertionError: /home/aro2ju/painted-markings-search/yolov6/short/images/labels/ is an invalid directory path!

My yaml file is configured in the following way

yaml:
is_coco: false
names:
- Sign
nc: 1
train: /home/aro2ju/painted-markings-search/yolov6/short/images/train/
val:   /home/aro2ju/painted-markings-search/yolov6/short/images/val/

My folder structure is created in this way ( I was not able to attach pictures for some reason)

yolov6
	short
		images
			train
				im1.png
				im2.png
			val
				im3.png
				im4.png
		labels
			train
				im1.txt
				im2.txt
			val
				im3.txt
				im4.txt
	
      YOLOv6
		Assets
		Config
		data

Any idea how to fix it?? I already tried putting the dataset in different folders, verified that image and labels matched

Thanks a lot

**Comment by mtjhl** [comment]
Hi, could you paste your `data/mask.yaml` here so we can try to locate the problem?

**Comment by oariasmx** [comment]
Hello!I don't have this error anymore, I changed my image and label folders to the same label as folders asset, data,etc see screenshot
![folderstructure_main](https://user-images.githubusercontent.com/87443801/182209357-2fafda3b-b226-4919-ad2a-b791f2069918.jpg)
![folderstructure](https://user-images.githubusercontent.com/87443801/182209420-6265b41f-a6c5-4bca-ac92-85c53314f8ae.jpg)

But now I have this other error (not enough values to unpack, expetcted 2 got 0)
![erorrexpected2](https://user-images.githubusercontent.com/87443801/182209445-e2faef21-83ac-4cb7-be0e-2a7924253eb0.jpg)



And find attached my yaml file

**Comment by oariasmx** [comment]
[mask.zip](https://github.com/meituan/YOLOv6/files/9236096/mask.zip)

**Comment by oariasmx** [comment]
Hello, I don't have this error anymore, ( I moved my image and labels folders to the same level as assets, data, etc), but now I have another error "trainvaldataset' object has no attribute 'img_paths' also I see another error wich mentions my images are corrupted, find screenshot

![noattribute img_paths](https://user-images.githubusercontent.com/87443801/182214155-2111384e-7c68-4cef-ab9e-11cb796a3f1c.jpg)

Here is my folder structure

![folderstructure_main](https://user-images.githubusercontent.com/87443801/182214193-cf727b4c-0d69-49bf-8983-f119b3b7f8e0.jpg)
![folderstructure](https://user-images.githubusercontent.com/87443801/182214210-e16af7b3-5e30-469b-8841-c697345bddd6.jpg)


Here my yaml file zipped
[mask (1).zip](https://github.com/meituan/YOLOv6/files/9236209/mask.1.zip)

**Comment by oariasmx** [comment]
Also, I don't know what happens but now having also this error 
![erorrexpected2](https://user-images.githubusercontent.com/87443801/182222025-cb0e8e8a-78a1-44d9-9aec-62b4a6a2f7e2.jpg)

**Comment by shensheng272** [comment]
you might check your ymal to follow

```
is_coco: False
names: ['Sign']
nc: 1
train: ./images/train
val: ./images/val
```
