### ISSUE TITLE
RuntimeError: Socket Timeout

### ISSUE THREAD

**Issue by danielchua2602** [meituan/YOLOv6#404]
During the checking formats of images, I run into a runtime error, RuntimeError: Socket Timeout.

Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    main(args)
  File "tools/train.py", line 104, in main
    trainer = Trainer(args, cfg, device)
  File "/home/user/Documents/Daniel/YOLOv6/yolov6/core/engine.py", line 47, in __init__
    self.train_loader, self.val_loader = self.get_data_loader(args, cfg, self.data_dict)
  File "/home/user/Documents/Daniel/YOLOv6/yolov6/core/engine.py", line 332, in get_data_loader
    train_loader = create_dataloader(train_path, args.img_size, args.batch_size // args.world_size, grid_size,
  File "/home/user/Documents/Daniel/YOLOv6/yolov6/data/data_load.py", line 40, in create_dataloader
    with torch_distributed_zero_first(rank):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/user/Documents/Daniel/YOLOv6/yolov6/utils/torch_utils.py", line 25, in torch_distributed_zero_first
    dist.barrier(device_ids=[local_rank])
  File "/home/user/Documents/yv6/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: Socket Timeout

**Comment by mtjhl** [comment]
What's your running commands?

**Comment by danielchua2602** [comment]
python3 -m torch.distributed.launch --nproc_per_node 2 tools/train.py --batch 64 --conf configs/yolov6s.py --data dataset.yaml --device 0,1 --epochs 1000 --output-dir checkpoints

**Comment by khwengXU** [comment]
You can check the local network or try other address/port.
