### ISSUE TITLE
Unexpectedly interrupted during training, set resume to True. Can not continue training

### ISSUE THREAD

**Issue by vajra0209** [meituan/YOLOv6#408]
HI,       Unexpectedly interrupted during training, set resume to True. Can not continue training

Traceback (most recent call last):
  File "train.py", line 115, in <module>
    main(args)
  File "train.py", line 104, in main
    trainer = Trainer(args, cfg, device)
  File "/root/YOLOv6-main/yolov6/core/engine.py", line 66, in __init__
    self.optimizer.load_state_dict(self.ckpt['optimizer'])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/optim/optimizer.py", line 138, in load_state_dict
    saved_groups = state_dict['param_groups']
TypeError: 'NoneType' object is not subscriptable

**Comment by vajra0209** [comment]
During training, halfway through the epoch, it is disconnected unexpectedly, resume=True cannot continue training

**Comment by mtjhl** [comment]
If you use `--resume`, this line will print the checkpoint path, https://github.com/meituan/YOLOv6/blob/ab76a39b9f89c15424ad6366794306239caaf573/tools/train.py#L58
What's the message it print when you are using resume?

**Comment by alumini** [comment]
> If you use `--resume`, this line will print the checkpoint path,
> 
> https://github.com/meituan/YOLOv6/blob/ab76a39b9f89c15424ad6366794306239caaf573/tools/train.py#L58
> 
> 
> What's the message it print when you are using resume?

Hi, where are we supposed to enter --resume.. is it in the training command only? or just in a new code block?

**Comment by 1843263375** [comment]
![image](https://user-images.githubusercontent.com/93514366/195601629-d0b91578-3da5-485a-9930-feadef1bc087.png)
你好，我在resume的时候，跟上面那位一样的错误，在我debug进一步判断的时候，发现我的ckpt文件，没有ema，updates以及optimizer，导致报错'NoneType' object is not subscriptable，应该怎么样解决啊，求解，谢谢了

**Comment by 1843263375** [comment]
![image](https://user-images.githubusercontent.com/93514366/195603224-139b6af1-14f2-41c0-b7bf-070bd6580aa7.png)
checkpoint_path

**Comment by np-n** [comment]
@vajra0209, Just go to `yolov6s_finetune.py`  and  edit `pretrained='weights/yolov6s.pt'` by `pretrained='./runs/train/exp/weights/last_ckpt.pt'`. And just run the command `!python tools/train.py --conf configs/yolov6s_finetune.py --<other_params>`
