### ISSUE TITLE
Error during inference

### ISSUE THREAD

**Issue by cmikke97** [meituan/YOLOv6#429]
After git clone (and requirements install) in Google Colab I just tried the model using the infer function with one of the provided images.
`!python tools/infer.py --weights /content/model-data/yolov6t.pt --source /content/YOLOv6/data/images/image3.jpg --save-txt`
The output was this:
```
Namespace(agnostic_nms=False, classes=None, conf_thres=0.4, device='0', half=False, hide_conf=False, hide_labels=False, img_size=640, iou_thres=0.45, max_det=1000, name='exp', project='runs/inference', save_dir=None, save_img=True, save_txt=True, source='/content/YOLOv6/data/images/image3.jpg', view_img=False, weights='/content/model-data/yolov6t.pt', yaml='data/coco.yaml')
Save directory already existed
Loading checkpoint from /content/model-data/yolov6t.pt

Fusing model...
Traceback (most recent call last):
  File "tools/infer.py", line 116, in <module>
    main(args)
  File "tools/infer.py", line 111, in main
    run(**vars(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "tools/infer.py", line 103, in run
    inferer = Inferer(source, weights, device, yaml, img_size, half)
  File "/content/YOLOv6/YOLOv6/yolov6/core/inferer.py", line 46, in __init__
    self.model(torch.zeros(1, 3, *self.img_size).to(self.device).type_as(next(self.model.model.parameters())))  # warmup
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/YOLOv6/YOLOv6/yolov6/layers/common.py", line 360, in forward
    y, _ = self.model(im)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/YOLOv6/YOLOv6/yolov6/models/yolo.py", line 44, in forward
    x = self.detect(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/YOLOv6/YOLOv6/yolov6/models/effidehead.py", line 101, in forward
    x, self.stride, self.grid_cell_size, self.grid_cell_offset, device=x[0].device, is_eval=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1208, in __getattr__
    type(self).__name__, name))
AttributeError: 'Detect' object has no attribute 'grid_cell_size'
```

One month ago the same code was working without issues.

**Comment by shensheng272** [comment]
`grid_cell_size` will init in `Detect` when load model. If you git clone latest code, you might need to download latest model weights. V0.1.0 weights could not be used in v0.2.0

**Comment by cmikke97** [comment]
That was it. Thank you!
