### ISSUE TITLE
你好，作者，最新0.2版本，eval.py怎么评估不出结果？

### ISSUE THREAD

**Issue by Wisdom2wisdom** [meituan/YOLOv6#448]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\executable_code\YOLO\yoloV62022\YOLOv6-main\tools\eval.py", line 7, in <module>
    import torch
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\__init__.py", line 123, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

一直这样，我以增加虚拟内存空间，调整batch，还是没变动。

**Comment by shensheng272** [comment]
你好  请确认  torch.cuda.is_available() 
如果使用cpu推理  请设置对应的参数  
使用的运行脚本具体是？

**Comment by Chilicyy** [comment]
@Wisdom2wisdom 请问这边有尝试过batchsize设为1时是否能运行成功吗

**Comment by Wisdom2wisdom** [comment]
> 
你好
batchsize减少1能在yolos.pt正常运行，
但我利用另外的backbone在train.py做预训练模型之后，并在infer.py依然能进行正常推理，为什么在eval.py不能正常评估？


Traceback (most recent call last):
  File "E:/executable_code/YOLO/yoloV62022/YOLOv6-main/tools/eval.py", line 138, in <module>
    main(args)
  File "E:/executable_code/YOLO/yoloV62022/YOLOv6-main/tools/eval.py", line 133, in main
    run(**vars(args))
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:/executable_code/YOLO/yoloV62022/YOLOv6-main/tools/eval.py", line 122, in run
    model = val.init_model(model, weights, task)
  File "E:\executable_code\YOLO\yoloV62022\YOLOv6-main\yolov6\core\evaler.py", line 78, in init_model
    LOGGER.info("Model Summary: {}".format(get_model_info(model, self.img_size)))
  File "E:\executable_code\YOLO\yoloV62022\YOLOv6-main\yolov6\utils\torch_utils.py", line 105, in get_model_info
    flops, params = profile(deepcopy(model), inputs=(img,), verbose=False)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\thop\profile.py", line 211, in profile
    model(*inputs)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\executable_code\YOLO\yoloV62022\YOLOv6-main\yolov6\models\yolo.py", line 39, in forward
    x = self.backbone(x)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\executable_code\YOLO\yoloV62022\YOLOv6-main\yolov6\models\efficientrep.py", line 303, in forward
    x = self.ERBlock_5(x)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\executable_code\YOLO\yoloV62022\YOLOv6-main\yolov6\layers\module.py", line 468, in forward
    max_ghost = self.block(x)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\executable_code\YOLO\yoloV62022\YOLOv6-main\yolov6\layers\module.py", line 422, in forward
    ghost = self.ghost(x)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\executable_code\YOLO\yoloV62022\YOLOv6-main\yolov6\layers\module.py", line 111, in forward
    x1 = self.primary_conv(x)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\yolov6\lib\site-packages\torch\nn\modules\conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (2 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size

**Comment by Wisdom2wisdom** [comment]
> 你好 请确认 torch.cuda.is_available() 如果使用cpu推理 请设置对应的参数 使用的运行脚本具体是？

谢谢，已经解决
