### ISSUE TITLE
Issues with Exporting to ONNX with end-to-end flag

### ISSUE THREAD

**Issue by amishra791** [meituan/YOLOv6#455]
Hi, I am trying to export my YOLOv6 model to TensorRT as outlined [here](https://github.com/meituan/YOLOv6/tree/main/deploy/ONNX#end2end-export). 

I ran the command: 
`python ./deploy/ONNX/export_onnx.py     --weights runs/train/exp_501/weights/[best_ckpt.pt](http://best_ckpt.pt/)  --img 640 --batch 1 --end2end --trt-version 8`, but am running into the following error: 

```
/home/adityamishrav5/anaconda3/lib/python3.9/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/home/adityamishrav5/Desktop/ir_camera/YOLOv6/./deploy/ONNX/export_onnx.py", line 75, in <module>
    y = model(img)  # dry run
  File "/home/adityamishrav5/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/adityamishrav5/Desktop/ir_camera/YOLOv6/yolov6/models/end2end.py", line 262, in forward
    x = self.end2end(x)
  File "/home/adityamishrav5/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/adityamishrav5/Desktop/ir_camera/YOLOv6/yolov6/models/end2end.py", line 231, in forward
    box = x[:, :, :4]
TypeError: list indices must be integers or slices, not tuple
```

Looking at the code more closely, it seems that the yolo model is [returning a list of tensors](https://github.com/meituan/YOLOv6/blob/main/yolov6/models/end2end.py#L258) (instead of a tensor or a numpy array). 

Any thoughts on how to fix this?

**Comment by shensheng272** [comment]
Thanks for the bug report, fix in https://github.com/meituan/YOLOv6/commit/21e0f289e3e604174aba4511845442dbf9e34a48

**Comment by amishra791** [comment]
> ..

Hi, I get a new error after applying the changes. 

```
/home/adityamishrav5/anaconda3/lib/python3.9/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

Starting to export ONNX...
/home/adityamishrav5/Desktop/ir_camera/YOLOv6/yolov6/assigners/anchor_generator.py:12: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for i, stride in enumerate(fpn_strides):
/home/adityamishrav5/Desktop/ir_camera/YOLOv6/yolov6/models/end2end.py:259: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  x, _ = self.model(x)
ONNX export failure: not enough values to unpack (expected 2, got 1)

Export complete (3.81s)

You can export tensorrt engine use trtexec tools.
Command is:
trtexec --onnx=runs/train/exp_501/weights/best_ckpt.onnx --saveEngine=runs/train/exp_501/weights/best_ckpt.engine
```

**Comment by shensheng272** [comment]
New commit https://github.com/meituan/YOLOv6/commit/16301c059d2305b12e66531defdf07413108f651 fix the different model out when eval onnx.

**Comment by amishra791** [comment]
> New commit [7420f55](https://github.com/meituan/YOLOv6/commit/7420f554f861c1134c4e83645589bdbbc6c4b72a) fix the different model out when eval onnx.

Thanks for your quick fixes!

The export now runs successfully, but I get multiple warnings of the type: 
`WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.`

Is this something I need to be worried about? How can I check to see if my model is working correctly?

**Comment by triple-Mu** [comment]
> > New commit [7420f55](https://github.com/meituan/YOLOv6/commit/7420f554f861c1134c4e83645589bdbbc6c4b72a) fix the different model out when eval onnx.
> 
> Thanks for your quick fixes!
> 
> The export now runs successfully, but I get multiple warnings of the type: `WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.`
> 
> Is this something I need to be worried about? How can I check to see if my model is working correctly?

It does not matter!
