### ISSUE TITLE
QAT Inference Speed is low

### ISSUE THREAD

**Issue by haritsahm** [meituan/YOLOv6#485]
Hi I tried to follow your steps for QAT training and deploy from [tools/qat](https://github.com/meituan/YOLOv6/blob/main/tools/qat/README.md) but the inference speed using TRT-INT8 is lower than TRT-FP16.

- Train model from RepOpt steps (hs -> repopt) then QAT training
- The YOLOv6s - RepOpt exported in half precision (`export_onnx.py --half`) using batch 1
- The YOLOv6s - RepOpt QAT must be sanitized using `polygraphy surgeon sanitize` to handle `Invalid Node - Identity_1` [TensorRT#2163](https://github.com/NVIDIA/TensorRT/issues/2163#issuecomment-1187700734). Exported using batch 1

### Environment
Docker: `nvcr.io/nvidia/pytorch:22.06-py3`, `nvcr.io/nvidia/pytorch:22.08-py3`
GPU: T4 (510.47.03)

### YOLOv6s - RepOpt FP16 Half (22.06)
```
[09/20/2022-03:06:22] [I] === Performance summary ===
[09/20/2022-03:06:22] [I] Throughput: 303.765 qps
[09/20/2022-03:06:22] [I] Latency: min = 2.36255 ms, max = 3.19653 ms, mean = 3.01113 ms, median = 3.05286 ms, percentile(99%) = 3.18408 ms
[09/20/2022-03:06:22] [I] End-to-End Host Latency: min = 2.37451 ms, max = 5.7771 ms, mean = 5.21482 ms, median = 5.44073 ms, percentile(99%) = 5.68359 ms
[09/20/2022-03:06:22] [I] Enqueue Time: min = 0.842285 ms, max = 2.30225 ms, mean = 1.2249 ms, median = 1.12842 ms, percentile(99%) = 1.87402 ms
[09/20/2022-03:06:22] [I] H2D Latency: min = 0.204834 ms, max = 0.307373 ms, mean = 0.216156 ms, median = 0.2146 ms, percentile(99%) = 0.234253 ms
[09/20/2022-03:06:22] [I] GPU Compute Time: min = 2.13794 ms, max = 2.96729 ms, mean = 2.77868 ms, median = 2.8208 ms, percentile(99%) = 2.95605 ms
[09/20/2022-03:06:22] [I] D2H Latency: min = 0.013916 ms, max = 0.0263672 ms, mean = 0.0162924 ms, median = 0.0163574 ms, percentile(99%) = 0.0178223 ms
[09/20/2022-03:06:22] [I] Total Host Walltime: 3.0089 s
[09/20/2022-03:06:22] [I] Total GPU Compute Time: 2.53971 s
[09/20/2022-03:06:22] [I] Explanations of the performance metrics are printed in the verbose logs.
[09/20/2022-03:06:22] [I] 
&&&& PASSED TensorRT.trtexec [TensorRT v8003] # trtexec --explicitBatch --fp16 --inputIOFormats=fp16:chw --outputIOFormats=fp16:chw --workspace=1024 --avgRuns=1024 --warmUp=1000 --loadEngine=best_ckpt_half.engine
```
### YOLOv6s - RepOpt FP16 Half (22.08)
```
[09/20/2022-03:10:05] [I] === Performance summary ===
[09/20/2022-03:10:05] [I] Throughput: 351.129 qps
[09/20/2022-03:10:05] [I] Latency: min = 2.94495 ms, max = 3.21655 ms, mean = 3.07959 ms, median = 3.0752 ms, percentile(99%) = 3.21045 ms
[09/20/2022-03:10:05] [I] Enqueue Time: min = 0.720825 ms, max = 1.58423 ms, mean = 1.01606 ms, median = 0.99353 ms, percentile(99%) = 1.33716 ms
[09/20/2022-03:10:05] [I] H2D Latency: min = 0.206055 ms, max = 0.321289 ms, mean = 0.219982 ms, median = 0.220276 ms, percentile(99%) = 0.234863 ms
[09/20/2022-03:10:05] [I] GPU Compute Time: min = 2.71094 ms, max = 2.97986 ms, mean = 2.84321 ms, median = 2.83838 ms, percentile(99%) = 2.97229 ms
[09/20/2022-03:10:05] [I] D2H Latency: min = 0.0144043 ms, max = 0.0219727 ms, mean = 0.0163944 ms, median = 0.0163574 ms, percentile(99%) = 0.0183105 ms
[09/20/2022-03:10:05] [I] Total Host Walltime: 3.00744 s
[09/20/2022-03:10:05] [I] Total GPU Compute Time: 3.00243 s
[09/20/2022-03:10:05] [W] * GPU compute time is unstable, with coefficient of variance = 1.83987%.
[09/20/2022-03:10:05] [W]   If not already in use, locking GPU clock frequency or adding --useSpinWait may improve the stability.
[09/20/2022-03:10:05] [I] Explanations of the performance metrics are printed in the verbose logs.
[09/20/2022-03:10:05] [I] 
&&&& PASSED TensorRT.trtexec [TensorRT v8402] # trtexec --explicitBatch --fp16 --inputIOFormats=fp16:chw --outputIOFormats=fp16:chw --workspace=1024 --avgRuns=1024 --warmUp=1000 --saveEngine=best_ckpt_half_2208.engine --onnx=best_ckpt_sanitized.onnx
````

### YOLOv6s - RepOpt QAT FP16 (22.08)
```[09/20/2022-03:39:55] [I] === Performance summary ===
[09/20/2022-03:39:55] [I] Throughput: 241.645 qps
[09/20/2022-03:39:55] [I] Latency: min = 4.25781 ms, max = 4.43701 ms, mean = 4.36289 ms, median = 4.34814 ms, percentile(99%) = 4.42822 ms
[09/20/2022-03:39:55] [I] Enqueue Time: min = 1.04712 ms, max = 3.22949 ms, mean = 1.73453 ms, median = 1.58789 ms, percentile(99%) = 3.0249 ms
[09/20/2022-03:39:55] [I] H2D Latency: min = 0.206787 ms, max = 0.249756 ms, mean = 0.218862 ms, median = 0.217773 ms, percentile(99%) = 0.234741 ms
[09/20/2022-03:39:55] [I] GPU Compute Time: min = 4.02295 ms, max = 4.19678 ms, mean = 4.12801 ms, median = 4.1106 ms, percentile(99%) = 4.18774 ms
[09/20/2022-03:39:55] [I] D2H Latency: min = 0.0144043 ms, max = 0.0187988 ms, mean = 0.0160149 ms, median = 0.015625 ms, percentile(99%) = 0.0178223 ms
[09/20/2022-03:39:55] [I] Total Host Walltime: 3.01268 s
[09/20/2022-03:39:55] [I] Total GPU Compute Time: 3.00519 s
[09/20/2022-03:39:55] [I] Explanations of the performance metrics are printed in the verbose logs.
[09/20/2022-03:39:55] [I] 
&&&& PASSED TensorRT.trtexec [TensorRT v8402] # trtexec --explicitBatch --fp16 --int8 --inputIOFormats=fp16:chw --outputIOFormats=fp16:chw --workspace=1024 --avgRuns=1024 --warmUp=1000 --saveEngine=best_ckpt_half_2208.engine --onnx=best_ckpt_bs1_graph_opt_sanitized.onnx --percentile=99 --streams=1
```

**Comment by lippman1125** [comment]
@haritsahm please use follow command to export onnx
`python3 qat_export.py --weights yolov6s_v2_reopt_43.1.pt --quant-weights yolov6s_v2_reopt_qat_43.0.pt --graph-opt --export-batch-size 1`

**Comment by haritsahm** [comment]
@lippman1125 Oh I forgot to mention that I am using a custom dataset for this model

**Comment by haritsahm** [comment]
Quick update. After testing using different docker version, I'am finally able to produce the similar result to your report.

Command run:
```
trtexec --workspace=1024 --percentile=99 --streams=1 --int8 --fp16 --avgRuns=10 --onnx=best_ckpt_bs1_graph_opt.onnx --calib=calibration.cache --inputIOFormats=fp16:chw --outputIOFormats=fp16:chw
```

### ONNX Exported Model Using nvcr.io/nvidia/pytorch:21.12-py3

| Inference Docker Version | Throughput (qps) | 
| ---------------------------------- | ----------------------- | 
| nvcr.io/nvidia/pytorch:21.12-py3 | 558.427 |
| nvcr.io/nvidia/pytorch:22.04-py3 | 558.807 |
| nvcr.io/nvidia/pytorch:22.06-py3 | 544.789 |
| nvcr.io/nvidia/pytorch:22.08-py3 | 496.185 |

### ONNX Exported Model Using nvcr.io/nvidia/pytorch:22.04-py3

- I have to sanitized the model before running trt inference `polygraphy surgeon sanitize best_ckpt_bs1_graph_opt.onnx --fold-constants -o best_ckpt_bs1_graph_opt-sanitized.onnx `

| Inference Docker Version | Throughput (qps) | 
| ---------------------------------- | ----------------------- | 
| nvcr.io/nvidia/pytorch:21.12-py3 | 181.126 |
| nvcr.io/nvidia/pytorch:22.04-py3 | 197.28 |
| nvcr.io/nvidia/pytorch:22.04-py3 | 198.204 |
| nvcr.io/nvidia/pytorch:22.08-py3 | 255.394 |

### ONNX Exported Model Using nvcr.io/nvidia/pytorch:22.04-py3
Raise error, I think this is pytorch related issue.
```
Traceback (most recent call last):
  File "qat_export.py", line 84, in <module>
    qat_mAP = yolov6_evaler.eval(model)
  File "yolov6-trainer/tools/qat/../../tools/partial_quantization/eval.py", line 47, in eval
    pred_result, vis_outputs, vis_paths = self.val.predict_model(model, self.val_loader, self.task)
  File "yolov6-trainer/tools/qat/../../yolov6/core/evaler.py", line 131, in predict_model
    outputs, _ = model(imgs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "yolov6-trainer/tools/qat/../../yolov6/models/yolo.py", line 45, in forward
    x = self.neck(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "yolov6-trainer/tools/qat/../../yolov6/models/reppan.py", line 105, in forward
    upsample_feat0 = self.upsample0(fpn_out0)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "yolov6-trainer/tools/qat/../../yolov6/layers/common.py", line 137, in forward
    return self.upsample_transpose(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_quantization/nn/modules/quant_conv.py", line 341, in forward
    output_padding = self._output_padding(input, output_size, self.stride, self.padding, self.kernel_size)
TypeError: _output_padding() missing 1 required positional argument: 'num_spatial_dims'
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
```

Could you please share your training and inference environment using a Dockerfile and update it to this repo? I think this would be helpful for others @lippman1125 @xingyueye

**Comment by xingyueye** [comment]
@haritsahm Nice work👍  We would release a stable env docker or the version list later.

**Comment by haritsahm** [comment]
@xingyueye Thank you, I'll close the issue since it is related to pytorch/onnx problem. I hope you can test and reproduce the result using the latest nvidia-pytorch docker environments.
