### ISSUE TITLE
AttributeError: 'RepVGGBlock' object has no attribute 'conv'

### ISSUE THREAD

**Issue by wanyne-yyds** [meituan/YOLOv6#528]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）  

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

使用 partial_quant.py 量化部分代码报错如下：
```bash
Skip Layer detect.proj_conv
op amax =  6.2489, amax = -1.0000
op amax =  6.2489, amax =  6.2489
amax =  6.2489
Traceback (most recent call last):
  File "./tools/partial_quantization/partial_quant.py", line 92, in <module>
    ops = [get_module(model_ptq, op_name) for op_name in sub_fusion_list]
  File "./tools/partial_quantization/partial_quant.py", line 92, in <listcomp>
    ops = [get_module(model_ptq, op_name) for op_name in sub_fusion_list]
  File "/home/ckn/Code/YOLOv6/tools/partial_quantization/utils.py", line 18, in get_module
    cur_mod = getattr(cur_mod, s)
  File "/home/ckn/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'RepVGGBlock' object has no attribute 'conv'
```

**Comment by lippman1125** [comment]
@wanyne-yyds which model do you use? v6s_reopt or v6s?

**Comment by lippman1125** [comment]
@wanyne-yyds ops' name in op_concat_fusion_list are from v6s_reopt, if you use v6s to apply partial ptq, you need to modify ops'name in op_concat_fusion_list.

**Comment by semihhdemirel** [comment]
@wanyne-yyds I used v6s_repopt. But I still encounter the same error. Can you explain more detail, what should i do for this error? What exactly should be written in the op_concat_fusion_list.

**Comment by BouchikhiYousra** [comment]
I have the exact same issue but I'm using v6n_repopt
