### ISSUE TITLE
训练yolov6s RepOpt出现的问题

### ISSUE THREAD

**Issue by LuoPeng-CV** [meituan/YOLOv6#556]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

当我训练RepOpt版本的yolov6s时出现以下问题，
##################### Re-initialize #############
Traceback (most recent call last):
  File "tools/train.py", line 126, in <module>
    main(args)
  File "tools/train.py", line 111, in main
    trainer = Trainer(args, cfg, device)
  File "/home/syang/luopeng/YOLOv6-main/yolov6/core/engine.py", line 58, in __init__
    self.optimizer = RepVGGOptimizer(model, scales, args, cfg, reinit=reinit)
  File "/home/syang/luopeng/YOLOv6-main/yolov6/utils/RepOptimizer.py", line 113, in __init__
    self.reinitialize(scales, convs, use_identity_scales_for_reinit)
  File "/home/syang/luopeng/YOLOv6-main/yolov6/utils/RepOptimizer.py", line 121, in reinitialize
    kernel_1x1 = nn.Conv2d(in_channels, out_channels, 1, device=conv3x3.weight.device)
TypeError: __init__() got an unexpected keyword argument 'device'

训练指令为：
python tools/train.py --batch 32 --conf configs/repopt/yolov6s_opt.py --data data.yaml --device 0

any advices? thank you!

**Comment by LuoPeng-CV** [comment]
pytorch版本需要1.9.0以上
