### ISSUE TITLE
训练时报目录问题

### ISSUE THREAD

**Issue by jia0511** [meituan/YOLOv6#57]
Traceback (most recent call last):
  File "/home/jack/data1/project/yolov6_0625/tools/train.py", line 14, in <module>
    from yolov6.core.engine import Trainer
  File "/home/jack/data1/project/yolov6_0625/yolov6/core/engine.py", line 16, in <module>
    import tools.eval as eval
ModuleNotFoundError: No module named 'tools.eval'
Traceback (most recent call last):
  File "/home/jack/data1/project/yolov6_0625/tools/train.py", line 14, in <module>
    from yolov6.core.engine import Trainer
  File "/home/jack/data1/project/yolov6_0625/yolov6/core/engine.py", line 16, in <module>
    import tools.eval as eval
ModuleNotFoundError: No module named 'tools.eval'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 18950) of binary: /home/jack/anaconda3/bin/python

**Comment by Chilicyy** [comment]
hi, do you start training under the ROOT directory($YOLOv6)?
