### ISSUE TITLE
yolov6_utils.py,how can i issue this problem?

### ISSUE THREAD

**Issue by krida1** [meituan/YOLOv6#574]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Traceback (most recent call last):
  File "prepare_slicing_traindata.py", line 7, in <module>
    from yolov6.utils.slicing import get_slice_bboxes, annotation_inside_slice
ModuleNotFoundError: No module named 'yolov6.utils'

### Additional

Traceback (most recent call last):
  File "prepare_slicing_traindata.py", line 7, in <module>
    from yolov6.utils.slicing import get_slice_bboxes, annotation_inside_slice
ModuleNotFoundError: No module named 'yolov6.utils'

**Comment by Chilicyy** [comment]
Before starting, you can add the directory path of YOLOv6 to PYTHONPATH by `export PYTHONPATH=$your_YOLOv6_dir:$PYTHONPATH` or `export PYTHONPATH=$PYTHONPATH:`pwd``.

**Comment by krida1** [comment]
> PYTHONPATH=$your_YOLOv6_dir:$PYTHONPATH
是这个意思吗，为什么还是没有用呢
$E:\Desktop\yolo\YOLOv6:$PYTHONPATH
![image](https://user-images.githubusercontent.com/91596567/198051199-c10018d6-0edc-47ad-b195-f0b84e72bcb4.png)

**Comment by Chilicyy** [comment]
@krida1 hi, 在网上找到一个设置pycharm中设置Pythonpath的教程，你可以试试：

1、File->Setting

2、Project：XXX->Project Interpreter

3、在右边的Project Interpreter的下拉框中选择Show All...

4、在弹出的对话框中，点击右边“Show paths for the selected interpreter”对应的按钮。

5、在新弹出的对话框中，点击‘＋’对应的按钮，添加新的路径（“Interpreter Paths”）。
————————————————
版权声明：本文为CSDN博主「roughman9999」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/roughman9999/article/details/79458262

**Comment by krida1** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 10, in <module>
    from yolov6.core.engine import Trainer
ModuleNotFoundError: No module named 'yolov6.core'
添加了这行代码都没有，还有把yolov6设置成了根目录也不行，是哪里有问题呢
ROOT = os.getcwd()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
# sys.path.append('/opt/data/private/github/yolo/YOLOv6/')

**Comment by shensheng272** [comment]
可以先试下在命令行下是否可以执行。
如果命令行可以执行，则应该是pyrcharm路径配置问题，可以单独搜索相关的信息。大概率是设置工作目录的问题

**Comment by krida1** [comment]
> 

命令行也不可以运行，就只可以右键运行才不会报错

**Comment by wysunrise2** [comment]
> @krida1 hi, 在网上找到一个设置pycharm中设置Pythonpath的教程，你可以试试：
> 
> 1、File->Setting
> 
> 2、Project：XXX->Project Interpreter
> 
> 3、在右边的Project Interpreter的下拉框中选择Show All...
> 
> 4、在弹出的对话框中，点击右边“Show paths for the selected interpreter”对应的按钮。
> 
> 5、在新弹出的对话框中，点击‘＋’对应的按钮，添加新的路径（“Interpreter Paths”）。 ———————————————— 版权声明：本文为CSDN博主「roughman9999」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。 原文链接：https://blog.csdn.net/roughman9999/article/details/79458262

看了下文件目录结构，这里的yolov6模块应该指的是和tools文件夹同层的yolov6文件夹，把这个yolov6文件夹复制到tools文件夹内，它就可以直接被访问到了。如图
![image](https://user-images.githubusercontent.com/82127901/215961674-9bb4be35-e3c7-4d0b-9285-0bfc0e0616d9.png)
