### ISSUE TITLE
当我训练QAT时（运行 configs/repopt/yolov6s_opt_qat.py文件）遇到如图问题

### ISSUE THREAD

**Issue by Muke6** [meituan/YOLOv6#596]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

训练时报错如图，我运行命令为： python tools/train.py --batch 1 --conf configs/repopt/yolov6s_opt_qat.py --data data/dataset.yaml --quant --calib --teacher_model_path runs/train/exp13/weights/best_ckpt.pt --distill --distill_feat --epochs 10

### Additional

![微信截图_20221107204943](https://user-images.githubusercontent.com/89955551/200314976-9004a58f-eb90-4948-9009-31240da78b19.png)

**Comment by LuoPeng-CV** [comment]
torch降版本可解决

**Comment by zahidzqj** [comment]
当我使用自己的数据以及opt权重，并从说明文档中下载了yolov6s_v2_scale.pt，执行PTQ操作：python tools/train_qat.py  --data ./data/dataset.yaml   --conf configs/repopt/yolov6s_opt_qat.py --quant  --calib

Traceback (most recent call last):
  File "tools/train_qat.py", line 127, in <module>
    main(args)
  File "tools/train_qat.py", line 115, in main
    trainer.calibrate(cfg)
  File "/data/YOLOv6/yolov6/core/engine.py", line 500, in calibrate
    ptq_calibrate(self.model, self.train_loader, cfg)
  File "/data/YOLOv6/tools/qat/qat_utils.py", line 59, in ptq_calibrate
    compute_amax(model, method=cfg.ptq.histogram_amax_method, percentile=cfg.ptq.histogram_amax_percentile)
  File "/data/YOLOv6/tools/qat/qat_utils.py", line 50, in compute_amax
    module.load_calib_amax(**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 237, in load_calib_amax
    raise RuntimeError(err_msg + " Passing 'strict=False' to `load_calib_amax()` will ignore the error.")
RuntimeError: Calibrator returned None. This usually happens when calibrator hasn't seen any tensor. Passing 'strict=False' to `load_calib_amax()` will ignore the error.
Using 1 GPU for training... 
这是因为什么呀？

**Comment by ChenGongfu** [comment]
> torch降版本可解决

which version of torch to use to solve this problem
