### ISSUE TITLE
Convert .pth to torch script 

### ISSUE THREAD

**Issue by dinosaurtirex** [meituan/YOLOv6#597]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Hello! Is there any way to converted trained weights to torchscript?

### Additional

Hello! Is there any way to converted trained weights to torchscript? I wrote some script:

```
import torch
import torchvision

def export_torchscript(path: str):
    device = torch.device("cuda:0")
    model:dict = torch.load(path)
    model = model['model'].to(device)
    vals = torch.zeros(1,3,640,480,dtype=torch.float16).to(device) 
    model.eval()
    ts = torch.jit.trace(
        model, 
        vals,
        strict=False
    ).to(device)
    d = {"shape":im.shape,
        "stride":int(max(model.stride)), 
        "names":model.names}
    extra_files = {'config.txt': json.dumps(d)}
    ts.save(str("new.pt"), _extra_files=extra_files)
    return file, None


if __name__ == '__main__':
    export_torchscript(path="runs/train/exp30/weights/best_stop_aug_ckpt.pt")

```

but it returns error: 

```
List inputs to traced functions must have consistent element type. Found Tensor and List[Tensor]
```

**Comment by mtjhl** [comment]
which line does this error occurs?
`List inputs to traced functions must have consistent element type. Found Tensor and List[Tensor]`

**Comment by dinosaurtirex** [comment]
> which line does this error occurs? `List inputs to traced functions must have consistent element type. Found Tensor and List[Tensor]`

Hello! Thanks for you're time. Near down i put full error log, but anwer for your question, error is upcoming from torch.jit.trace line and raising inside of torch module itself 

```
import torch
import torchvision

def export_torchscript(path: str):
    device = torch.device("cuda:0")
    model:dict = torch.load(path)
    model = model['model'].to(device)
    vals = torch.zeros(1,3,640,480,dtype=torch.float16).to(device) 
    model.eval()
    
    ts = torch.jit.trace(model, vals,strict=False).to(device) 
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        ^^^^ here error is rasing 
                        
    d = {"shape":im.shape,
        "stride":int(max(model.stride)), 
        "names":model.names}
    extra_files = {'config.txt': json.dumps(d)}
    ts.save(str("new.pt"), _extra_files=extra_files)
    return file, None


if __name__ == '__main__':
    export_torchscript(path="runs/train/exp30/weights/best_stop_aug_ckpt.pt")
```

```
Traceback (most recent call last):
  File "/home/kirill/python-projects/python-nn/pth_to_pt.py", line 24, in <module>
    export_torchscript(path="runs/train/exp30/weights/best_stop_aug_ckpt.pt")
  File "/home/kirill/python-projects/python-nn/pth_to_pt.py", line 10, in export_torchscript
    ts = torch.jit.trace(
  File "/home/kirill/python-projects/venv/lib/python3.10/site-packages/torch/jit/_trace.py", line 759, in trace
    return trace_module(
  File "/home/kirill/python-projects/venv/lib/python3.10/site-packages/torch/jit/_trace.py", line 976, in trace_module
    module._c._create_method_from_trace(
RuntimeError: Tracer cannot infer type of [tensor([[[7.7383e+00, 1.4959e+01, 1.7352e+01,  ..., 1.7105e-02,
          2.3422e-02, 2.0218e-02],
         [1.4266e+01, 1.2422e+01, 2.5250e+01,  ..., 1.6983e-02,
          3.2227e-02, 2.7740e-02],
         [1.7344e+01, 8.2930e+00, 3.0000e+01,  ..., 2.1210e-02,
          3.4302e-02, 2.8656e-02],
         ...,
         [4.2059e+02, 5.9080e+02, 1.0394e+02,  ..., 1.3222e-02,
          5.4199e-02, 3.5278e-02],
         [4.4205e+02, 5.9350e+02, 7.9406e+01,  ..., 1.4839e-02,
          5.3406e-02, 3.7598e-02],
         [4.5650e+02, 5.9519e+02, 4.8188e+01,  ..., 1.3901e-02,
          5.5206e-02, 3.3844e-02]]], device='cuda:0', grad_fn=<CatBackward0>), [tensor([[[[3.6719, 3.0352, 3.3750,  ..., 3.5117, 3.1797, 3.2461],
          [3.8672, 3.1953, 3.4805,  ..., 3.6094, 3.2461, 3.4492],
          [4.0117, 3.0508, 3.0703,  ..., 3.4023, 3.0547, 3.1406],
          ...,
          [4.4727, 3.6133, 3.5195,  ..., 3.5703, 3.1953, 3.2578],
          [4.2344, 3.4453, 3.2461,  ..., 3.3438, 3.3359, 3.6230],
          [2.2949, 1.0752, 0.8467,  ..., 1.0215, 0.8037, 1.8574]],

         [[4.2070, 3.4375, 3.3516,  ..., 3.3008, 3.5352, 4.1211],
          [4.1797, 3.5410, 3.3457,  ..., 2.9102, 3.4062, 3.9922],
          [4.2617, 3.7676, 3.4922,  ..., 3.2461, 3.7773, 4.1992],
          ...,
          [4.1914, 3.5625, 3.1055,  ..., 2.8242, 3.5352, 3.9688],
          [4.1523, 3.6953, 3.5039,  ..., 3.0977, 3.7969, 4.0352],
          [4.1797, 3.6113, 3.4258,  ..., 3.2617, 3.8047, 4.0430]],

         [[6.1055, 5.5977, 5.8828,  ..., 5.5273, 5.8516, 5.4219],
          [4.4922, 5.7305, 5.0000,  ..., 4.8359, 5.2070, 4.0664],
          [4.4062, 4.5000, 2.7969,  ..., 3.5117, 3.6523, 2.1289],
          ...,
          [4.4375, 4.8555, 2.7617,  ..., 3.2266, 3.2402, 2.2227],
          [5.1172, 5.4141, 3.4355,  ..., 4.1953, 4.1836, 2.3711],
          [4.5586, 6.9375, 4.3398,  ..., 4.9883, 4.9062, 5.5938]],

         ...,

         [[3.1641, 3.5312, 3.3730,  ..., 3.5605, 3.5234, 3.4121],
          [3.1914, 3.4336, 3.0371,  ..., 3.3809, 3.6719, 3.0742],
          [2.9336, 3.3340, 2.7148,  ..., 3.1660, 3.0469, 2.6738],
          ...,
          [2.9102, 3.3516, 3.0605,  ..., 3.0215, 3.2539, 2.6367],
          [3.1777, 3.9199, 3.6621,  ..., 3.8828, 3.7148, 3.1797],
          [3.2891, 3.6094, 3.3008,  ..., 3.2246, 3.1406, 2.7070]],

         [[2.4141, 2.0918, 2.8047,  ..., 2.7324, 2.6152, 1.8154],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.3416],
          [0.0000, 0.0000, 0.6226,  ..., 1.2305, 0.1399, 0.6084],
          ...,
          [0.1921, 0.0000, 0.0000,  ..., 0.2754, 0.0930, 0.7388],
          [0.0469, 0.0000, 0.0000,  ..., 0.7363, 0.0820, 0.0000],
          [0.8506, 0.7876, 1.4326,  ..., 2.3516, 2.2227, 2.0098]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 2.2539, 0.8369,  ..., 1.0605, 0.8735, 0.0000],
          [0.0000, 1.9551, 0.1816,  ..., 1.1172, 0.0176, 0.0000],
          ...,
          [0.0000, 1.4453, 0.9546,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.2571, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.4370, 0.3281, 0.0000,  ..., 0.0000, 0.3628, 0.0000]]]],
       device='cuda:0', dtype=torch.float16, grad_fn=<ReluBackward0>), tensor([[[[2.6855e+00, 1.9160e+00, 1.5518e+00,  ..., 1.8115e+00,
           1.9141e+00, 2.1680e+00],
          [2.7891e+00, 1.7520e+00, 1.6230e+00,  ..., 1.4980e+00,
           1.4619e+00, 1.7969e+00],
          [2.7266e+00, 2.0039e+00, 1.5684e+00,  ..., 1.7480e+00,
           1.5303e+00, 2.0586e+00],
          ...,
          [3.1523e+00, 2.3066e+00, 2.4414e+00,  ..., 1.8828e+00,
           2.0137e+00, 2.1543e+00],
          [2.9336e+00, 2.3086e+00, 2.0840e+00,  ..., 1.9561e+00,
           1.8242e+00, 2.2422e+00],
          [3.1016e+00, 2.3145e+00, 2.3867e+00,  ..., 2.1621e+00,
           2.2207e+00, 2.2539e+00]],

         [[0.0000e+00, 6.6895e-01, 1.0254e-02,  ..., 0.0000e+00,
           2.3164e+00, 2.0000e+00],
          [0.0000e+00, 1.8921e-01, 0.0000e+00,  ..., 0.0000e+00,
           3.3887e+00, 2.1465e+00],
          [0.0000e+00, 5.2344e-01, 0.0000e+00,  ..., 0.0000e+00,
           3.3359e+00, 2.3262e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           3.3203e+00, 2.6152e+00],
          [0.0000e+00, 8.7158e-02, 0.0000e+00,  ..., 0.0000e+00,
           2.6855e+00, 2.4004e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           2.2344e+00, 2.2832e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           2.9980e-01, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 8.7402e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 3.3618e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         ...,

         [[3.7930e+00, 4.9492e+00, 4.3750e+00,  ..., 4.3906e+00,
           4.1055e+00, 3.9141e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 0.0000e+00, 9.6802e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [7.5195e-02, 2.5635e-01, 0.0000e+00,  ..., 3.0176e-01,
           1.7297e-01, 2.1362e-01],
          [3.3276e-01, 6.2866e-03, 2.4463e-01,  ..., 7.3438e-01,
           5.3027e-01, 1.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 4.3945e-03, 1.2793e+00,  ..., 7.1387e-01,
           4.6265e-01, 0.0000e+00],
          [0.0000e+00, 1.1797e+00, 1.9492e+00,  ..., 1.4316e+00,
           1.5586e+00, 0.0000e+00],
          ...,
          [0.0000e+00, 8.9062e-01, 1.2100e+00,  ..., 8.9258e-01,
           7.4805e-01, 0.0000e+00],
          [0.0000e+00, 8.1543e-01, 1.6279e+00,  ..., 9.0820e-01,
           1.0781e+00, 0.0000e+00],
          [0.0000e+00, 1.2686e+00, 1.5176e+00,  ..., 1.1152e+00,
           8.3203e-01, 0.0000e+00]],

         [[6.8115e-01, 4.3457e-01, 1.9958e-02,  ..., 6.5137e-01,
           7.0801e-01, 1.9492e+00],
          [8.9355e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 2.1641e+00],
          [9.5166e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 2.0859e+00],
          ...,
          [2.0781e+00, 0.0000e+00, 1.8726e-01,  ..., 3.1982e-01,
           1.6663e-02, 2.6562e+00],
          [1.7822e+00, 1.9214e-01, 4.3579e-01,  ..., 1.0186e+00,
           7.3535e-01, 2.9082e+00],
          [3.0391e+00, 1.6484e+00, 1.7666e+00,  ..., 2.4121e+00,
           2.2480e+00, 3.3672e+00]]]], device='cuda:0', dtype=torch.float16,
       grad_fn=<ReluBackward0>), tensor([[[[0.0000, 0.5698, 0.1060,  ..., 0.0161, 0.2759, 0.7246],
          [0.2368, 1.0020, 0.7100,  ..., 0.9136, 0.7524, 0.8833],
          [0.0508, 0.5396, 0.2275,  ..., 0.1208, 0.1819, 0.9800],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2886],
          [0.1396, 0.3857, 0.0000,  ..., 0.0645, 0.5010, 0.8975],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.2314, 0.5938]],

         [[0.0835, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2561],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [1.8076, 1.7734, 1.1758,  ..., 0.7285, 0.5264, 0.5420],
          [1.4141, 1.7715, 1.3203,  ..., 0.7529, 0.2400, 0.5684],
          [3.9668, 4.9180, 4.8281,  ..., 4.3242, 3.9492, 3.0820]],

         [[0.9165, 0.0811, 0.2661,  ..., 0.1162, 0.0925, 0.1812],
          [0.3809, 0.0349, 0.1045,  ..., 0.0000, 0.0000, 0.1748],
          [0.3745, 0.0725, 0.0981,  ..., 0.0061, 0.0000, 0.2886],
          ...,
          [0.0430, 0.1177, 0.1863,  ..., 0.1650, 0.1843, 0.5469],
          [0.0513, 0.0615, 0.0967,  ..., 0.0642, 0.0234, 0.2483],
          [0.0000, 0.0000, 0.0090,  ..., 0.0000, 0.0000, 0.0930]],

         ...,

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[2.7207, 1.6943, 1.9023,  ..., 1.7334, 1.9160, 2.1172],
          [1.5781, 0.9863, 1.1992,  ..., 1.0967, 1.1963, 1.4678],
          [1.8643, 1.2461, 1.4561,  ..., 1.3447, 1.3750, 1.5352],
          ...,
          [1.4883, 1.0469, 1.3145,  ..., 1.2568, 1.2334, 1.4766],
          [1.7295, 1.2334, 1.5176,  ..., 1.4492, 1.3760, 1.5957],
          [1.9922, 1.6084, 1.7471,  ..., 1.6816, 1.7305, 1.9668]],

         [[1.3760, 0.0128, 0.2830,  ..., 0.0312, 0.3818, 0.0000],
          [1.1270, 0.6440, 0.6313,  ..., 0.6748, 1.7422, 0.0000],
          [1.8047, 1.4658, 1.2686,  ..., 1.2939, 2.3789, 0.0000],
          ...,
          [1.7510, 1.4785, 0.9141,  ..., 1.0273, 2.5586, 0.0000],
          [1.5244, 1.4092, 0.8003,  ..., 0.8003, 2.7891, 0.0000],
          [1.1377, 1.1240, 0.5312,  ..., 0.5996, 2.6582, 0.0000]]]],
       device='cuda:0', dtype=torch.float16, grad_fn=<ReluBackward0>)]]
:List inputs to traced functions must have consistent element type. Found Tensor and List[Tensor]

```

**Comment by dinosaurtirex** [comment]
> which line does this error occurs? `List inputs to traced functions must have consistent element type. Found Tensor and List[Tensor]`

Also for more detail describe i put my neural network params which model is training on:

```
data_path: data/dataset.yaml
conf_file: configs/yolov6n_finetune.py
img_size: 640
batch_size: 16
epochs: 5000
workers: 8
device: '0'
eval_interval: 20
eval_final_only: false
heavy_eval_range: 50
check_images: false
check_labels: false
output_dir: ./runs/train
name: exp
dist_url: env://
gpu_count: 0
local_rank: -1
resume: false
write_trainbatch_tb: false
stop_aug_last_n_epoch: 15
save_ckpt_on_last_n_epoch: -1
distill: false
distill_feat: false
quant: false
calib: false
teacher_model_path: null
temperature: 20
rank: -1
world_size: 1
save_dir: runs/train/exp30

```
