### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocotools._mask'

### ISSUE THREAD

**Issue by Shaoli7** [meituan/YOLOv6#600]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

[](url)我使用pycharm打开最新的代码，运行train.py文件出现报错ModuleNotFoundError: No module named 'pycocotools._mask'，试了很多方法，都不行，您可以给个建议吗？
"D:\Program Files\Anaconda3\envs\pytorch1.8.1\python.exe" "D:/Program Files/Anaconda3/envs/pytorch1.8.1/pycocotools/mask.py"
Traceback (most recent call last):
  File "D:/Program Files/Anaconda3/envs/pytorch1.8.1/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ModuleNotFoundError: No module named 'pycocotools._mask'
[环境配置里也有pycocotools包](url)

**Comment by Chilicyy** [comment]
您好，看起来pycocotools没有安装成功，可以尝试源码安装的方法。

**Comment by Shaoli7** [comment]
> 您好，看起来pycocotools没有安装成功，可以尝试源码安装的方法。

好的，感谢您，经过重新安装几次好了。但是在训练运行中完成一个epoch后出现了TypeError: 'numpy.float64' object cannot be interpreted as an integer这个问题。
重新安装了，也按照网上的降低了numpy的版本，还是不行，具体错误信息如下：
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "F:/MrLi/YOLOv6-main/tools/train.py", line 126, in <module>
    main(args)
  File "F:/MrLi/YOLOv6-main/tools/train.py", line 116, in main
    trainer.train()
  File "F:\MrLi\YOLOv6-main\yolov6\core\engine.py", line 99, in train
    self.train_in_loop(self.epoch)
  File "F:\MrLi\YOLOv6-main\yolov6\core\engine.py", line 119, in train_in_loop
    self.eval_and_save()
  File "F:\MrLi\YOLOv6-main\yolov6\core\engine.py", line 157, in eval_and_save
    self.eval_model()
  File "F:\MrLi\YOLOv6-main\yolov6\core\engine.py", line 192, in eval_model
    results, vis_outputs, vis_paths = eval.run(self.data_dict,
  File "D:\Program Files\Anaconda3\envs\pytorch1.8.1\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\MrLi\YOLOv6-main\tools\eval.py", line 154, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "F:\MrLi\YOLOv6-main\yolov6\core\evaler.py", line 262, in eval_model
    cocoEval = COCOeval(anno, pred, 'bbox')
  File "D:\Program Files\Anaconda3\envs\pytorch1.8.1\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "D:\Program Files\Anaconda3\envs\pytorch1.8.1\lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "D:\Program Files\Anaconda3\envs\pytorch1.8.1\lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 180, in linspace
  File "D:\Program Files\Anaconda3\envs\pytorch1.8.1\lib\site-packages\numpy\core\function_base.py", line 120, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
非常期待您的解答

**Comment by Chilicyy** [comment]
看起来还是需要重新安装cocoapi,可以参考这篇教程：https://blog.csdn.net/flyfish1986/article/details/104513632
如果紧急的话，可以在评估时不用cocoapi，改用另一种方式做评估。具体可参考这个配置文件的设置 https://github.com/meituan/YOLOv6/blob/main/configs/experiment/yolov6n_with_eval_params.py#L60 ， 将`do_coco_metric`设为False , `do_pr_metric`设为True。

**Comment by Shaoli7** [comment]
> 看起来还需要重新安装 cocoapi，请参考：[https](https://blog.csdn.net/flyfish1986/article/details/104513632) ://blog.csdn.net/flyfish1986/article/details/104513632 紧急的话，可以在评估 cocoapi 时用另一种方式评估具体可以参考这个配置文件的设置https://github.com/meituan/YOLOv6/blob/main/configs/experiment/yolov6n_with_eval_params.py#L60，将`do_coco_metric`设为False，`do_pr_metric`设为True。

好的，我去试下，谢谢您的指导，我想问下要是用另一种方式评估cocoapi的话，对精度会有影响吗？

**Comment by shensheng272** [comment]
> > 看起来还需要重新安装 cocoapi，请参考：[https](https://blog.csdn.net/flyfish1986/article/details/104513632) ://blog.csdn.net/flyfish1986/article/details/104513632 紧急的话，可以在评估 cocoapi 时用另一种方式评估具体可以参考这个配置文件的设置[https://github.com/meituan/YOLOv6/blob/main/configs/experiment/yolov6n_with_eval_params.py#L60，将`do_coco_metric`设为False，`do_pr_metric`设为True。](https://github.com/meituan/YOLOv6/blob/main/configs/experiment/yolov6n_with_eval_params.py#L60%EF%BC%8C%E5%B0%86%60do_coco_metric%60%E8%AE%BE%E4%B8%BAFalse%EF%BC%8C%60do_pr_metric%60%E8%AE%BE%E4%B8%BATrue%E3%80%82)
> 
> 好的，我去试下，谢谢您的指导，我想问下要是用另一种方式评估cocoapi的话，对精度会有影响吗？

影响不大，只是注意对比的时候尽量使用一种评估方法
