### ISSUE TITLE
Bug in img-size argument of infer

### ISSUE THREAD

**Issue by AliRezaBeigy** [meituan/YOLOv6#646]
### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar feature requests.

### Description

by running following command
```
!python tools/infer.py --weights runs/train/exp/weights/best_ckpt.pt --source dataset/images/1.jpg --yaml dataset.yaml --img-size 416--device 0 
```
the following exception raised
```
Namespace(agnostic_nms=False, classes=None, conf_thres=0.4, device='0', half=False, hide_conf=False, hide_labels=False, img_size=[416], iou_thres=0.45, max_det=1000, name='exp', not_save_img=False, project='runs/inference', save_dir=None, save_txt=False, source='dataset/images/train/7e97f49e613a59a70b833e4c0b2c1c04_jpg.rf.4521f7f4426d59e3817609ee10e78393.jpg', view_img=False, weights='runs/train/exp/weights/best_ckpt.pt', yaml='dataset.yaml')
Save directory already existed
Loading checkpoint from runs/train/exp/weights/best_ckpt.pt

Fusing model...
Switch model to deploy modality.
Traceback (most recent call last):
  File "tools/infer.py", line 116, in <module>
    main(args)
  File "tools/infer.py", line 111, in main
    run(**vars(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "tools/infer.py", line 103, in run
    inferer = Inferer(source, weights, device, yaml, img_size, half)
  File "/content/YOLOv6/yolov6/core/inferer.py", line 50, in __init__
    self.model(torch.zeros(1, 3, *self.img_size).to(self.device).type_as(next(self.model.model.parameters())))  # warmup
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/YOLOv6/yolov6/layers/common.py", line 360, in forward
    y, _ = self.model(im)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/YOLOv6/yolov6/models/yolo.py", line 39, in forward
    x = self.backbone(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/YOLOv6/yolov6/models/efficientrep.py", line 98, in forward
    x = self.stem(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/YOLOv6/yolov6/layers/common.py", line 209, in forward
    return self.nonlinearity(self.se(self.rbr_reparam(inputs)))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[1, 1, 3, 416] to have 3 channels, but got 1 channels instead
```

As I figure out the implementation of argument parsing in infer is different from train and eval tools.
I think the default value should be changed to int and make an array and pass it into Inferer

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mtjhl** [comment]
Can you download a model from https://github.com/meituan/YOLOv6/releases/download/0.2.0/yolov6n.pt
 and try to run commands
```
python tools/infer.py --source  data/images/image1.jpg --weights yolov6n.pt --img-size 416
```
To see whether there is problem.

**Comment by AliRezaBeigy** [comment]
@mtjhl 
https://colab.research.google.com/drive/17NBzpeQsqDHwptVU9rwbFaj3wtIRZ6A5?usp=sharing
as you can see in this Colab link the script crashed

**Comment by AliRezaBeigy** [comment]
Now I understand why it's not working
I must pass two dimensions with space as separation like below:
```
python tools/infer.py ... --img-size 416 416
```
