### ISSUE TITLE
ERROR in evaluate and save model.

### ISSUE THREAD

**Issue by jielanZhang** [meituan/YOLOv6#729]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

ERROR in evaluate and save model.
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "tools/train.py", line 130, in <module>
  File "tools/train.py", line 120, in main

  File "/home/YOLOv6-0.3.0/yolov6/core/engine.py", line 108, in train
    self.train_in_loop(self.epoch)
  File "/home/YOLOv6-0.3.0/yolov6/core/engine.py", line 128, in train_in_loop
    self.eval_and_save()
  File "/home/YOLOv6-0.3.0/yolov6/core/engine.py", line 172, in eval_and_save
    self.eval_model()
  File "/home/YOLOv6-0.3.0/yolov6/core/engine.py", line 207, in eval_model
    results, vis_outputs, vis_paths = eval.run(self.data_dict,
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/YOLOv6-0.3.0/tools/eval.py", line 154, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/home/YOLOv6-0.3.0/yolov6/core/evaler.py", line 315, in eval_model
    cocoEval.summarize()
  File "/usr/local/lib/python3.8/dist-packages/pycocotools/cocoeval.py", line 518, in summarize
    self.stats = summarize()
  File "/usr/local/lib/python3.8/dist-packages/pycocotools/cocoeval.py", line 487, in _summarizeDets
    stats[2] = _summarize(1, iouThr=.75, maxDets=self.params.maxDets[2])
  File "/usr/local/lib/python3.8/dist-packages/pycocotools/cocoeval.py", line 468, in _summarize
    s = s[:,:,:,t,:]
IndexError: index 5 is out of bounds for axis 3 with size 4

**Comment by mtjhl** [comment]
请问您是在什么数据上报的错误。看着像是模型输出的类别 ID 超出了标签的类别数量。

**Comment by jielanZhang** [comment]
自己的数据集和coco128都是这个报错

**Comment by jielanZhang** [comment]
不过现在已经解决了，我在windows上没问题，服务器上有这个问题，然后最后定位到pycocotools,我把windows上envs里面的pycocotools拉到服务器对应的文件夹下面，就没问题了
