### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'

### ISSUE THREAD

**Issue by jia0511** [meituan/YOLOv6#73]
`Training start...

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
  0%|          | 0/82 [00:00<?, ?it/s]                                          /home/jack/anaconda3/lib/python3.9/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
      0/99     1.868     1.227     5.353     2.089: 100%|██████████| 82/82 [00:4
Inferencing model in val datasets.: 100%|███████| 18/18 [00:16<00:00,  1.08it/s]

Evaluating speed.

Evaluating mAP by pycocotools.
Saving ./runs/train/exp/predictions.json...
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
Loading and preparing results...
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.

Training completed in 0.017 hours.
Traceback (most recent call last):
  File "/home/jack/data1/project/yolov6_0625/tools/train.py", line 87, in <module>
    main(args)
  File "/home/jack/data1/project/yolov6_0625/tools/train.py", line 77, in main
    trainer.train()
  File "/home/jack/data1/project/yolov6_0625/yolov6/core/engine.py", line 62, in train
    self.train_in_loop()
  File "/home/jack/data1/project/yolov6_0625/yolov6/core/engine.py", line 81, in train_in_loop
    self.eval_and_save()
  File "/home/jack/data1/project/yolov6_0625/yolov6/core/engine.py", line 107, in eval_and_save
    self.eval_model()
  File "/home/jack/data1/project/yolov6_0625/yolov6/core/engine.py", line 126, in eval_model
    results = eval.run(self.data_dict,
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jack/data1/project/yolov6_0625/tools/eval.py", line 76, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/home/jack/data1/project/yolov6_0625/yolov6/core/evaler.py", line 129, in eval_model
    pred = anno.loadRes(pred_json)
  File "/home/jack/anaconda3/lib/python3.9/site-packages/pycocotools/coco.py", line 327, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc22ad3d790>
Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home/jack/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
`

**Comment by jia0511** [comment]
The Problem happened in training myself data refer to https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md

**Comment by mingwz** [comment]
I have the same problem, did you solve it?

**Comment by jia0511** [comment]
I changed my python version to 3.8 ,but also occur the error as follow:

Training start...

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
  0%|          | 0/82 [00:00<?, ?it/s]                                          /home/jack/anaconda3/envs/pytorch_for_yolov6/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
      0/99     1.868     1.227     5.353     2.089: 100%|██████████| 82/82 [00:4
Inferencing model in val datasets.: 100%|███████| 18/18 [00:16<00:00,  1.08it/s]

Evaluating speed.

Evaluating mAP by pycocotools.
Saving ./runs/train/exp/predictions.json...
loading annotations into memory...
Done (t=0.12s)
creating index...
index created!
Loading and preparing results...
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.

Training completed in 0.017 hours.
Traceback (most recent call last):
  File "tools/train.py", line 87, in <module>
    main(args)
  File "tools/train.py", line 77, in main
    trainer.train()
  File "/home/jack/data1/project/yolov6_0625/yolov6/core/engine.py", line 62, in train
    self.train_in_loop()
  File "/home/jack/data1/project/yolov6_0625/yolov6/core/engine.py", line 81, in train_in_loop
    self.eval_and_save()
  File "/home/jack/data1/project/yolov6_0625/yolov6/core/engine.py", line 107, in eval_and_save
    self.eval_model()
  File "/home/jack/data1/project/yolov6_0625/yolov6/core/engine.py", line 126, in eval_model
    results = eval.run(self.data_dict,
  File "/home/jack/anaconda3/envs/pytorch_for_yolov6/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jack/data1/project/yolov6_0625/tools/eval.py", line 76, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/home/jack/data1/project/yolov6_0625/yolov6/core/evaler.py", line 129, in eval_model
    pred = anno.loadRes(pred_json)
  File "/home/jack/anaconda3/envs/pytorch_for_yolov6/lib/python3.8/site-packages/pycocotools/coco.py", line 327, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set

**Comment by mingwz** [comment]
#76

**Comment by mendoza-G** [comment]
This is an erro happended due to torch1.11.0 version + torchvision0.12+cu11XX , just uninstall torch and torch visison` pip uninstall torch torchvision `
then install `pip install torch==1.10.0+cu113 torchvision==0.11.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html` 
This I' ve tried fixed this problem.

**Comment by jia0511** [comment]
@mendoza-G ,
I modified the corresponding pytorch version according to your introduction, but the above error still occurs. For the data format, I refer to https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md.

**Comment by mendoza-G** [comment]
> @mendoza-G , I modified the corresponding pytorch version according to your introduction, but the above error still occurs. For the data format, I refer to https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md.

Check your cuda version as well, this solution worked for me, it seems your data format is not righht, why not download COCO2017 to test your environment qualified and treat that as a reference.

**Comment by jia0511** [comment]
@mendoza-G 
I believe that the coco data test is definitely no problem, but I currently need to train my own data set. Since the official manual is provided, it should be able to train normally, otherwise it is a bug, and if the official requirements.txt manual has pytorch and torchvision versions Specific requirements can specify the fixed version.

**Comment by jia0511** [comment]
Dear all,

I had solve the issue refer to https://github.com/meituan/YOLOv6/issues/76
