### ISSUE TITLE
about QAT errors

### ISSUE THREAD

**Issue by TallyH0** [meituan/YOLOv6#732]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

i'm trying to QAT using [https://github.com/meituan/YOLOv6/blob/main/tools/qat/README.md](url) tutorial.

so far, RepOPT train done. PTQ is done.
however, when i run QAT command using yolov6s_opt_qat.py config file.

Traceback (most recent call last):
  File "/home/vc/yolov6_3.0/tools/train.py", line 128, in <module>
    main(args)
  File "/home/vc/yolov6_3.0/tools/train.py", line 113, in main
    trainer = Trainer(args, cfg, device)
  File "/home/vc/yolov6_3.0/yolov6/core/engine.py", line 62, in __init__
    self.teacher_model = self.get_teacher_model(args, cfg, self.num_classes, device)
  File "/home/vc/yolov6_3.0/yolov6/core/engine.py", line 395, in get_teacher_model
    model = build_model(cfg, nc, device, fuse_ab=teacher_fuse_ab)
  File "/home/vc/yolov6_3.0/yolov6/models/yolo.py", line 129, in build_model
    model = Model(cfg, channels=3, num_classes=num_classes, fuse_ab=fuse_ab, distill_ns=distill_ns).to(device)
  File "/home/vc/yolov6_3.0/yolov6/models/yolo.py", line 23, in __init__
    self.backbone, self.neck, self.detect = build_network(config, channels, num_classes, num_layers, fuse_ab=fuse_ab, distill_ns=distill_ns)
  File "/home/vc/yolov6_3.0/yolov6/models/yolo.py", line 116, in build_network
    anchors_init = config.model.head.anchors_init
  File "/home/vc/yolov6_3.0/yolov6/utils/config.py", line 30, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'anchors_init'

i got this error.

**Comment by mtjhl** [comment]
What is your running command? 
Maybe it is bug we need to fix. Add anchor init accoording the link bellow may fix this error.
https://github.com/meituan/YOLOv6/blob/c8c841fa85e474da07555414ce308a2ed4c28318/configs/yolov6s.py#L25

**Comment by TallyH0** [comment]
here is command.

python tools\train.py --conf configs\repopt\yolov6s_opt_qat.py --quant --distill --distill_feat --batch 16 --epochs 10 --teacher_model_path weights\best_ckpt_opt.pt --data data\dataset.yaml

teacher_model is equal to pretrained model in config file.

**Comment by llopen** [comment]
我用最新代码也有这个错误，anchors_init这个值设置过了，使用 python tools/train.py --data data_my/data.yaml --conf configs/repopt/yolov6n_opt_qat.py --quant --distill --distill_feat --batch 16 --epoch 10 --worker 0，完整错误：Traceback (most recent call last):
  File "tools/train.py", line 128, in <module>
    main(args)
  File "tools/train.py", line 113, in main
    trainer = Trainer(args, cfg, device)
  File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/core/engine.py", line 62, in __init__
    self.teacher_model = self.get_teacher_model(args, cfg, self.num_classes, device)
  File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/core/engine.py", line 395, in get_teacher_model
    model = build_model(cfg, nc, device, fuse_ab=teacher_fuse_ab)
  File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/models/yolo.py", line 128, in build_model
    model = Model(cfg, channels=3, num_classes=num_classes, fuse_ab=fuse_ab, distill_ns=distill_ns).to(device)
  File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/models/yolo.py", line 23, in __init__
    self.backbone, self.neck, self.detect = build_network(config, channels, num_classes, num_layers, fuse_ab=fuse_ab, distill_ns=distill_ns)
  File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/models/yolo.py", line 115, in build_network
    anchors_init = config.model.head.anchors_init
  File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/utils/config.py", line 30, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'anchors_init'

**Comment by llopen** [comment]
> What is your running command? Maybe it is bug we need to fix. Add anchor init accoording the link bellow may fix this error.
> 
> https://github.com/meituan/YOLOv6/blob/c8c841fa85e474da07555414ce308a2ed4c28318/configs/yolov6s.py#L25

我用最新代码也有这个错误，anchors_init这个值设置过了，使用 python tools/train.py --data data_my/data.yaml --conf configs/repopt/yolov6n_opt_qat.py --quant --distill --distill_feat --batch 16 --epoch 10 --worker 0，完整错误：Traceback (most recent call last):
File "tools/train.py", line 128, in
main(args)
File "tools/train.py", line 113, in main
trainer = Trainer(args, cfg, device)
File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/core/engine.py", line 62, in init
self.teacher_model = self.get_teacher_model(args, cfg, self.num_classes, device)
File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/core/engine.py", line 395, in get_teacher_model
model = build_model(cfg, nc, device, fuse_ab=teacher_fuse_ab)
File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/models/yolo.py", line 128, in build_model
model = Model(cfg, channels=3, num_classes=num_classes, fuse_ab=fuse_ab, distill_ns=distill_ns).to(device)
File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/models/yolo.py", line 23, in init
self.backbone, self.neck, self.detect = build_network(config, channels, num_classes, num_layers, fuse_ab=fuse_ab, distill_ns=distill_ns)
File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/models/yolo.py", line 115, in build_network
anchors_init = config.model.head.anchors_init
File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/utils/config.py", line 30, in getattr
raise ex
AttributeError: 'ConfigDict' object has no attribute 'anchors_init'

**Comment by TallyH0** [comment]
> What is your running command? Maybe it is bug we need to fix. Add anchor init accoording the link bellow may fix this error.
> 
> https://github.com/meituan/YOLOv6/blob/c8c841fa85e474da07555414ce308a2ed4c28318/configs/yolov6s.py#L25

fianlly solve this issue.

Add anchors_init in config file. and change model loading code in engine.py

and now it works!

**Comment by nomurakeiya** [comment]
hello
I have a same error!
When I use "python tools/train.py --batch 32 --conf configs/yolov6l6_finetune.py --data data/crowdhuman.yaml --fuse_ab --device 0"

Then this error happend.
"AttributeError: 'ConfigDict' object has no attribute 'anchors_init’ "

when I use yolov6_finetune.py, training prosses is started.

How to solve this error!
thanks.

**Comment by Chilicyy** [comment]
Hi, @nomurakeiya Fuse_ab mode is not supported for P6 models such as yolov6-l6, so you can not add `--fuse_ab` when you try to train P6 models.
