### ISSUE TITLE
量化感知训练进行到最后一步QAT时，AttributeError: 'ConfigDict' object has no attribute 'anchors_init'

### ISSUE THREAD

**Issue by llopen** [meituan/YOLOv6#737]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

使用 python tools/train.py --data data_my/data.yaml --conf configs/repopt/yolov6n_opt_qat.py --quant --distill --distill_feat --batch 16 --epoch 10 --worker 0，完整错误：Traceback (most recent call last):
  File "tools/train.py", line 128, in <module>
    main(args)
  File "tools/train.py", line 113, in main
    trainer = Trainer(args, cfg, device)
  File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/core/engine.py", line 62, in __init__
    self.teacher_model = self.get_teacher_model(args, cfg, self.num_classes, device)
  File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/core/engine.py", line 395, in get_teacher_model
    model = build_model(cfg, nc, device, fuse_ab=teacher_fuse_ab)
  File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/models/yolo.py", line 128, in build_model
    model = Model(cfg, channels=3, num_classes=num_classes, fuse_ab=fuse_ab, distill_ns=distill_ns).to(device)
  File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/models/yolo.py", line 23, in __init__
    self.backbone, self.neck, self.detect = build_network(config, channels, num_classes, num_layers, fuse_ab=fuse_ab, distill_ns=distill_ns)
  File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/models/yolo.py", line 115, in build_network
    anchors_init = config.model.head.anchors_init
  File "/home/wwh/project/obj_detect/YOLOv6-main1/yolov6/utils/config.py", line 30, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'anchors_init'

**Comment by jce2090** [comment]
最后怎么解决的呢

**Comment by OMG59E** [comment]
如何解决的呢？
