### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by tigerzjh** [meituan/YOLOv6#789]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

ERROR in training steps.
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "tools/train.py", line 129, in <module>
    main(args)
  File "tools/train.py", line 119, in main
    trainer.train()
  File "/home/zhangjianhu/codes_train_test/YOLOv6/yolov6/core/engine.py", line 112, in train
    self.train_in_loop(self.epoch)
  File "/home/zhangjianhu/codes_train_test/YOLOv6/yolov6/core/engine.py", line 126, in train_in_loop
    self.train_in_steps(epoch_num, self.step)
  File "/home/zhangjianhu/codes_train_test/YOLOv6/yolov6/core/engine.py", line 147, in train_in_steps
    preds, s_featmaps = self.model(images)
  File "/home/zhangjianhu/.custom/cuda11.3.1-cudnn8-devel-ubuntu20.04-py38-jupyter-pytorch1.11/envs/yolov5-6.1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhangjianhu/codes_train_test/YOLOv6/yolov6/models/yolo.py", line 35, in forward
    x = self.neck(x)
  File "/home/zhangjianhu/.custom/cuda11.3.1-cudnn8-devel-ubuntu20.04-py38-jupyter-pytorch1.11/envs/yolov5-6.1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhangjianhu/codes_train_test/YOLOv6/yolov6/models/reppan.py", line 632, in forward
    (x2, x1, x0) = input
ValueError: too many values to unpack (expected 3)

### Additional

训练命令
 python tools/train.py --batch 32 --conf configs/base/yolov6s_base_finetune.py --data data/porn/coco.yaml --fuse_ab --device 0 --epochs 2 --write_trainbatch_tb --stop_aug_last_n_epoch 1

**Comment by Chilicyy** [comment]
请问你是修改了配置文件，添加了 fuse_P2=True 吗？
