### ISSUE TITLE
训练自定义数据集时发生错误

### ISSUE THREAD

**Issue by Flacon12** [meituan/YOLOv6#812]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

你好，我在训练自己的训练集的时候，发生以下错误，请问我该怎么解决呢？
数据集的图片或labels中都没有0kb的文件
     Epoch  iou_loss  dfl_loss  cls_loss
    19/399    0.3965         0     1.048: 100%|██████████| 47/47 [00:25<00:00,  

     Epoch  iou_loss  dfl_loss  cls_loss
    20/399    0.3874         0     1.018: 100%|██████████| 47/47 [00:26<00:00,  
Inferencing model in train datasets.:   0%|               | 0/6 [00:00<?, ?it/s]
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "D:\YOLO_all_Version\YOLOv6-main\tools\train.py", line 128, in <module>
    main(args)
  File "D:\YOLO_all_Version\YOLOv6-main\tools\train.py", line 118, in main
    trainer.train()
  File "D:\YOLO_all_Version\YOLOv6-main\yolov6\core\engine.py", line 109, in train
    self.train_in_loop(self.epoch)
  File "D:\YOLO_all_Version\YOLOv6-main\yolov6\core\engine.py", line 129, in train_in_loop
    self.eval_and_save()
  File "D:\YOLO_all_Version\YOLOv6-main\yolov6\core\engine.py", line 173, in eval_and_save
    self.eval_model()
  File "D:\YOLO_all_Version\YOLOv6-main\yolov6\core\engine.py", line 208, in eval_model
    results, vis_outputs, vis_paths = eval.run(self.data_dict,
  File "D:\softmax\Anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\YOLO_all_Version\YOLOv6-main\tools\eval.py", line 153, in run
    pred_result, vis_outputs, vis_paths = val.predict_model(model, dataloader, task)
  File "D:\YOLO_all_Version\YOLOv6-main\yolov6\core\evaler.py", line 148, in predict_model
    pred_results.extend(self.convert_to_coco_format(outputs, imgs, paths, shapes, self.ids))
  File "D:\YOLO_all_Version\YOLOv6-main\yolov6\core\evaler.py", line 378, in convert_to_coco_format
    path, shape = Path(paths[i]), shapes[i][0]
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1

**Comment by Flacon12** [comment]
在源代码的基础上，除了修改训练参数，我还做了以下操作：
我想开启数据增强的方法，
1、在datasets.py文件57行的augment=False改为augment=True,
2、在data_load.py文件20行的augment=False改为augment=True
是不是我修改的这两处的原因？
如果是的话，我该怎样使用数据增强呢？

**Comment by shensheng272** [comment]
看修改位置，修改的是函数的默认传参。
训练过程实际调用的参数 'augment=True'   可以查看engine.py 的370行左右。

建议训练的时候参数加上'--check-images' 和 '--check-labels'
