### ISSUE TITLE
torch.load "yolov6l.pt" failed

### ISSUE THREAD

**Issue by 1224wxwx** [meituan/YOLOv6#827]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

When I tried to load yolov6l.pt (downloaded from https://github.com/meituan/YOLOv6/releases/download/0.3.0/yolov6l.pt), it failed with following error:

`Loading state_dict from weights/yolov6l.pt for fine-tuning...
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main(args)
  File "tools/train.py", line 127, in main
    trainer = Trainer(args, cfg, device)
  File "/workspace/YOLOv6-main/yolov6/core/engine.py", line 58, in __init__
    model = self.get_model(args, cfg, self.num_classes, device)
  File "/workspace/YOLOv6-main/yolov6/core/engine.py", line 421, in get_model
    model = load_state_dict(weights, model, map_location=device)
  File "/workspace/YOLOv6-main/yolov6/utils/checkpoint.py", line 13, in load_state_dict
    ckpt = torch.load(weights, map_location=map_location)
  File "/root/anaconda3/envs/fairmot/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/anaconda3/envs/fairmot/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/root/anaconda3/envs/fairmot/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'ConvWrapper' on <module 'yolov6.layers.common' from '/workspace/YOLOv6-main/yolov6/layers/common.py'>
`

**Comment by mtjhl** [comment]
您得从 release 页面下载最新的权重，0.4 版本的权重。
