### ISSUE TITLE
加载模型时出错

### ISSUE THREAD

**Issue by woshiwangyilei** [meituan/YOLOv6#831]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

加载模型时找不到一个模块，以下是报错：
Loading state_dict from weights/yolov6s.pt for fine-tuning...
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main(args)
  File "tools/train.py", line 127, in main
    trainer = Trainer(args, cfg, device)
  File "E:\data\code\YOLO\YOLOv6\yolov6\core\engine.py", line 58, in __init__
    model = self.get_model(args, cfg, self.num_classes, device)
  File "E:\data\code\YOLO\YOLOv6\yolov6\core\engine.py", line 421, in get_model
    model = load_state_dict(weights, model, map_location=device)
  File "E:\data\code\YOLO\YOLOv6\yolov6\utils\checkpoint.py", line 13, in load_state_dict
    ckpt = torch.load(weights, map_location=map_location)
  File "e:\data\code\YOLO\YOLOv6\.conda\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "e:\data\code\YOLO\YOLOv6\.conda\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "e:\data\code\YOLO\YOLOv6\.conda\lib\site-packages\torch\serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'SimConv' on <module 'yolov6.layers.common' from 'E:\\data\\code\\YOLO\\YOLOv6\\yolov6\\layers\\common.py'>

**Comment by Chilicyy** [comment]
#799
