### ISSUE TITLE
TypeError: cannot unpack non-iterable int object

### ISSUE THREAD

**Issue by pantelmen** [meituan/YOLOv6#861]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I train the model in custom data and in the last epochs it breaks with this error:
                                                           
ERROR in training steps.
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "/media/FastData/pmentesidis/yolov6/YOLOv6/tools/train.py", line 142, in <module>
    main(args)
  File "/media/FastData/pmentesidis/yolov6/YOLOv6/tools/train.py", line 132, in main
    trainer.train()
  File "/media/FastData/pmentesidis/yolov6/YOLOv6/yolov6/core/engine.py", line 121, in train
    self.train_one_epoch(self.epoch)
  File "/media/FastData/pmentesidis/yolov6/YOLOv6/yolov6/core/engine.py", line 134, in train_one_epoch
    for self.step, self.batch_data in self.pbar:
  File "/media/FastData/pmentesidis/anaconda3/envs/yolov6/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/media/FastData/pmentesidis/yolov6/YOLOv6/yolov6/data/data_load.py", line 111, in __iter__
    yield next(self.iterator)
  File "/media/FastData/pmentesidis/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/media/FastData/pmentesidis/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/media/FastData/pmentesidis/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/media/FastData/pmentesidis/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/media/FastData/pmentesidis/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/media/FastData/pmentesidis/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/FastData/pmentesidis/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/FastData/pmentesidis/yolov6/YOLOv6/yolov6/data/datasets.py", line 164, in __getitem__
    img, labels = random_affine(
  File "/media/FastData/pmentesidis/yolov6/YOLOv6/yolov6/data/data_augment.py", line 82, in random_affine
    height, width = new_shape
TypeError: cannot unpack non-iterable int object

**Comment by mtjhl** [comment]
What's your training commands?

**Comment by pantelmen** [comment]
python  /media/FastDatayolov6/YOLOv6/tools/train.py --batch 20 --conf  /media/FastData/yolov6/YOLOv6/configs/yolov6m6_finetune.py --data /media/FastData/yolov6/YOLOv6/20230629-new_dataset/data.yaml --device 0,1 --name 20230629yolo6m6
