### ISSUE TITLE
不能正常运行train.py，不清楚什么问题

### ISSUE THREAD

**Issue by taitanmm6666** [meituan/YOLOv6#863]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

YOLOv6-0.4.0> python tools/train.py --batch 4 --conf configs/yolov6n.py --data data/coco.yaml --device 0    
Traceback (most recent call last):
  File "D:\program file\PyCharm Community Edition 2023.1.1\project\YOLOv6-0.4.0\tools\train.py", line 128, in <module>
    main(args)
  File "D:\program file\PyCharm Community Edition 2023.1.1\project\YOLOv6-0.4.0\tools\train.py", line 101, in main
    cfg, device, args = check_and_init(args)
                        ^^^^^^^^^^^^^^^^^^^^
  File "D:\program file\PyCharm Community Edition 2023.1.1\project\YOLOv6-0.4.0\tools\train.py", line 87, in check_and_init
    device = select_device(args.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program file\PyCharm Community Edition 2023.1.1\project\YOLOv6-0.4.0\yolov6\utils\envs.py", line 32, in select_device
    assert torch.cuda.is_available()
AssertionError

我没有修改参数，直接运行的train.py，这个报错我也没看懂什么意思，麻烦解答一下。

### Additional

我也尝试使用自己的数据集，同样的问题

**Comment by mtjhl** [comment]
您的电脑是不是没有配置好 CUDA，如果没有 GPU ，可以试试 --device cpu

**Comment by taitanmm6666** [comment]
确实是cuda出现了问题，使用中途cuda丢失了，重新装了一遍之后已经可以了，谢谢
