### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by DonJ0n** [meituan/YOLOv6#876]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Everytime I try to run the training command I get the following error 
`Traceback (most recent call last):
  File "...\YOLOv6\tools\train.py", line 142, in <module>
    main(args)
  File "...YOLOv6\tools\train.py", line 115, in main
    cfg, device, args = check_and_init(args)
                        ^^^^^^^^^^^^^^^^^^^^
  File "...\Dis\YOLOv6\tools\train.py", line 101, in check_and_init    
    device = select_device(args.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\YOLOv6\yolov6\utils\envs.py", line 32, in select_device
    assert torch.cuda.is_available()
AssertionError`

I have made sure that my dataset is properly formatted and the yaml config file as well as the finetune.py file are edited accordingly. I am still new to machine learning and I do not really understand what I did wrong here

**Comment by mtjhl** [comment]
Do you have GPU on your computer, if not ,you can pass `--devices=cpu` to `train.py`

**Comment by DonJ0n** [comment]
Yes I have a 3060ti, Its telling me that the database structure is wrong even tho im quite sure I did it write. I recently had to format my computer and lost some stuff but Ill send you some more details shortly. thank you for the response.On 20 Jul 2023, at 15:13, liangliang ***@***.***> wrote:Do you have GPU on your computer, if not ,you can pass --devices=cpu to train.py—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
