### ISSUE TITLE
Calibrator returned None. This usually happens when calibrator hasn't seen any tensor. Passing 'strict=False' to `load_calib_amax()` will ignore the error.

### ISSUE THREAD

**Issue by panahikhas** [meituan/YOLOv6#879]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

## RuntimeError: Calibrator returned None. This usually happens when calibrator hasn't seen any tensor. Passing `'strict=False'` to `load_calib_amax()` will ignore the error.

I am trying to train your model and apply QAT on it. But when I am calibrating the model in the `tools/qat/qat_utils.py` that call the `collect_stats` function and then calls the `compute_amax` function errors.

The function `collect_stats` seems working well because in the terminal I watch that in size of `num_batches` it is receiving input to collect data. But after that in `compute_amax` it has error.

The error is:

```
E0718 16:22:00.375516 140192387998336 engine.py:178] ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "/home/i2027/Desktop/Panahi/detection/YOLOv6/yolo_tools/train.py", line 142, in <module>
    main(args)
  File "/home/i2027/Desktop/Panahi/detection/YOLOv6/yolo_tools/train.py", line 132, in main
    trainer.train()
  File "/home/i2027/Desktop/Panahi/detection/YOLOv6/yolov6/core/engine.py", line 172, in train
    self.before_epoch()
  File "/home/i2027/Desktop/Panahi/detection/YOLOv6/yolov6/core/engine.py", line 423, in before_epoch
    ptq_calibrate(self.model, self.train_loader, self.cfg)
  File "/home/i2027/Desktop/Panahi/detection/YOLOv6/yolo_tools/qat/qat_utils.py", line 61, in ptq_calibrate
    compute_amax(model, method='max')
  File "/home/i2027/Desktop/Panahi/detection/YOLOv6/yolo_tools/qat/qat_utils.py", line 47, in compute_amax
    module.load_calib_amax()
  File "/home/i2027/anaconda3/envs/p/lib/python3.10/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 237, in load_calib_amax
    raise RuntimeError(err_msg + " Passing 'strict=False' to `load_calib_amax()` will ignore the error.")
RuntimeError: Calibrator returned None. This usually happens when calibrator hasn't seen any tensor. Passing 'strict=False' to `load_calib_amax()` will ignore the error.
```

If I do the suggestion and set `strict=False` the max value of quantized layer set as NaN and mAP decreases a lot.

Is there any way to find why this error exists and how to solve it?

I also tested your `collect_stats` and `compute_amax` functions on other models and it works well but for you own model it doesn't work.

The only change I did is that the code in file `yolov6/core/engine.py` in the line 581 as `model.neck.upsample_enable_quant(cfg.ptq.num_bits, cfg.ptq.calib_method)` was commented because had errors and said that `RepPANNeck has no attribute upsample_enable_quant`. I thought maybe it is useful to say that.

## Environment

 - PyTorch Version: 2.0.1+cu118
 - CPU Architecture: x86
 - OS: Ubuntu 20.04
 - How I installed PyTorch: pip
 - Python version: 3.10.11
 - CUDA version: 12.1
 - GPU models and configuration: GeForce GTX 1080 - 11 GB
 - All pckages versions:

 -  - absl_py==1.4.0
 -  - addict==2.4.0
 -  - matplotlib==3.7.1
 -  - ncnn==1.0.20230517
 -  - numpy==1.24.1
 -  - onnx==1.14.0
 -  - onnx_simplifier==0.4.33
 -  - opencv_python==4.8.0.74
 -  - Pillow==9.3.0
 -  - Pillow==10.0.0
 -  - pycocotools==2.0.6
 -  - pycuda==2022.2.2
 -  - pytorch_quantization==2.1.2
 -  - PyYAML==6.0
 -  - PyYAML==6.0.1
 -  - Requests==2.31.0
 -  - seaborn==0.12.2
 -  - setuptools==67.8.0
 -  - thop==0.1.1.post2209072238
 -  - torch==2.0.1+cu118
 -  - torch_tensorrt==1.4.0
 -  - torchvision==0.15.2+cu118
 -  - tqdm==4.65.0

**Comment by rpa020** [comment]
Have you found a solution to this problem?
