### ISSUE TITLE
验证时，图片尺寸错误

### ISSUE THREAD

**Issue by Flacon12** [meituan/YOLOv6#895]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

我设置的--img-size=640，验证时打印出图片size=[54,3,672,672]，导致后面的torch.cat发生错误。骨干网络使用EfficientRep能验证成功，更改后的EfficientRep也成功运行了很多次，但这次没成功，不知道到底错在哪儿。
Inferencing model in train datasets.:   0%|               | 0/7 [00:01<?, ?it/s]
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "D:/zzz/YOLOv6-main/YOLOv6-main/tools/train.py", line 145, in <module>
    main(args)
  File "D:/zzz/YOLOv6-main/YOLOv6-main/tools/train.py", line 135, in main
    trainer.train()
  File "D:\zzz\YOLOv6-main\YOLOv6-main\yolov6\core\engine.py", line 122, in train
    self.after_epoch()
  File "D:\zzz\YOLOv6-main\YOLOv6-main\yolov6\core\engine.py", line 188, in after_epoch
    self.eval_model()
  File "D:\zzz\YOLOv6-main\YOLOv6-main\yolov6\core\engine.py", line 224, in eval_model
    results, vis_outputs, vis_paths = eval.run(self.data_dict,
  File "D:\anaconda\envs\hxs\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\zzz\YOLOv6-main\YOLOv6-main\tools\eval.py", line 158, in run
    pred_result, vis_outputs, vis_paths = val.predict_model(model, dataloader, task)
  File "D:\zzz\YOLOv6-main\YOLOv6-main\yolov6\core\evaler.py", line 128, in predict_model
    outputs, _ = model(imgs)
  File "D:\anaconda\envs\hxs\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\zzz\YOLOv6-main\YOLOv6-main\yolov6\models\yolo.py", line 37, in forward
    x = self.neck(x)
  File "D:\anaconda\envs\hxs\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\zzz\YOLOv6-main\YOLOv6-main\yolov6\models\giraffefpn.py", line 242, in forward
    x4 = torch.cat([x1, x24, x34], 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 21 but got size 22 for tensor number 2 in the list.

进程已结束,退出代码1

**Comment by Flacon12** [comment]
我发现是在data_augment.py中的letterbox函数有问题，最后打印出的img size=（672，672，3）

**Comment by Flacon12** [comment]
我直接在data_augment.py中的行加入new_shape = (640, 640)，直接写死，然后能成功训练后验证数据集，但我不知道这个方法是不是会对其他有影响，是不是正确的，可以的话请告诉我最正确的方法

**Comment by Flacon12** [comment]
自定的数据集图片尺寸时1280，训练参数的img-size=640
