### ISSUE TITLE
train.py coco based dataset fails with train.py: error: unrecognized arguments: --local-rank=7

### ISSUE THREAD

**Issue by egbertn** [meituan/YOLOv6#915]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I have pytorch 2.0.1+cu118 
it seems something is no longer supported.... 
Without hacking the existing code, starting a coco based training seems impossible

train.py: error: unrecognized arguments: --local-rank=7
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 3076) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/egbertnierop/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/egbertnierop/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/egbertnierop/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/egbertnierop/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/egbertnierop/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/egbertnierop/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------

**Comment by egbertn** [comment]
Solution is as follows
The documentation needs to be updated since the tutorial uses the old syntax, which ends with error above.
e.g.
torchrun tools/train.py --batch 128 --conf configs/yolov6n.py --data  ~/CarDD_COCO/data.yaml --epoch 100 --fuse_ab --device 0

**Comment by all-for-code** [comment]
> Solution is as follows The documentation needs to be updated since the tutorial uses the old syntax, which ends with error above. e.g. torchrun tools/train.py --batch 128 --conf configs/yolov6n.py --data ~/CarDD_COCO/data.yaml --epoch 100 --fuse_ab --device 0

Hi, @egbertn 
I think this approach only supports a single GPU and does not support multiple GPUs
This should be caused by the inconsistency between "--local_rank" and "--local-rank". To investigate the reason, it turns out that the torch2.0 version of launch.py contains all --local-rank。So you need to change the “--local_rank” in tool/train.py to “--local-rank”。 I hope this helps you。
![image](https://github.com/meituan/YOLOv6/assets/110803332/720c91c2-df5f-4972-8bc3-87e67c618004)
