### ISSUE TITLE
Index Error: list index out of range during training.

### ISSUE THREAD

**Issue by angela804** [meituan/YOLOv6#935]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Not sure why I got this error.
python tools/train.py --batch 8 --conf configs/yolov6n_seg.py --data data/custom.yaml --epochs 5

inputting this command gives me this error when it prompts in inferencing model in trained datasets

ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "C:\Users\GIGAbyte!\YOLOv6\tools\train.py", line 142, in <module>
    main(args)
  File "C:\Users\GIGAbyte!\YOLOv6\tools\train.py", line 132, in main
    trainer.train()
  File "C:\Users\GIGAbyte!\YOLOv6\yolov6\core\engine.py", line 125, in train
    self.after_epoch()
  File "C:\Users\GIGAbyte!\YOLOv6\yolov6\core\engine.py", line 201, in after_epoch
    self.ap = self.evaluate_results[3]
IndexError: list index out of range

**Comment by cayuso-skylark** [comment]
Same issue.

**Comment by angela804** [comment]
> Same issue.

i saw this repository. check the engine.py here. I was able to finish training when i changed the engine.py same as here
https://github.com/nirbarazida/YOLOv6

My only problem is that training data in each epoch are not recorded. i dont know im so confused. have you worked it out?

**Comment by Chilicyy** [comment]
hi @angela804 @cayuso-skylark  Are you using the latest code from the official YOLOv6 project?  
You can refer to this line :  https://github.com/meituan/YOLOv6/blob/d512ce7c4f103e8887960198505518bed404abdc/yolov6/core/engine.py#L189C51-L189C51

**Comment by angela804** [comment]
> hi @angela804 @cayuso-skylark Are you using the latest code from the official YOLOv6 project? You can refer to this line : https://github.com/meituan/YOLOv6/blob/d512ce7c4f103e8887960198505518bed404abdc/yolov6/core/engine.py#L189C51-L189C51

hey. thank you so much for this one. By any chance, do you also have info about this model to record losses at every epoch and the confusion matrix?

**Comment by MiksVasiljevs** [comment]
> hi @angela804 @cayuso-skylark Are you using the latest code from the official YOLOv6 project? You can refer to this line : https://github.com/meituan/YOLOv6/blob/d512ce7c4f103e8887960198505518bed404abdc/yolov6/core/engine.py#L189C51-L189C51

Hi @Chilicyy 

On the segmentation branch, it is self.ap = self.evaluate_results[3]. If this is not intended, could this be fixed by any chance?

https://github.com/meituan/YOLOv6/blob/463d8e7bee6ebbceaf8484c9a2a0468164b63338/yolov6/core/engine.py#L201
