### ISSUE TITLE
during segmentation model training [IndexError: list index out of range]

### ISSUE THREAD

**Issue by sulaiman1988** [meituan/YOLOv6#981]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

what is the best solution for this error that occurs when running the segmentation model?
User
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main(args)
  File "tools/train.py", line 132, in main
    trainer.train()
  File "/data/Workspaces/d/YOLOv6/yolov6/core/engine.py", line 125, in train
    self.after_epoch()
  File "/data/Workspaces/d/YOLOv6/yolov6/core/engine.py", line 201, in after_epoch
    self.ap = self.evaluate_results[3]
IndexError: list index out of range

**Comment by Chilicyy** [comment]
Hi @sulaiman1988 We have fixed the error, by changing the list index 3 to -1.
