### ISSUE TITLE
yolov6 face模型，怎么导出onnx?

### ISSUE THREAD

**Issue by xinsuinizhuan** [meituan/YOLOv6#984]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

我使用跟检测模型同样的导出命令，导出失败：
python ./deploy/ONNX/export_onnx.py --weights yolov6n_face.pt --img 640 --batch 1 --simplify

错误：
Namespace(weights='yolov6n_face.pt', img_size=[640, 640], batch_size=1, half=False, inplace=False, simplify=True, dynamic_batch=False, end2end=False, trt_version=8, ort=False, with_preprocess=False, topk_all=100, iou_thres=0.45, conf_thres=0.4, device='0')
Loading checkpoint from yolov6n_face.pt
Traceback (most recent call last):
  File "G:\Item_done\yolo\yolo5\yolov6\YOLOv6-yolov6-face\deploy\ONNX\export_onnx.py", line 50, in <module>
    model = load_checkpoint(args.weights, map_location=device, inplace=True, fuse=True)  # load FP32 model
  File "G:\Item_done\yolo\yolo5\yolov6\YOLOv6-yolov6-face\yolov6\utils\checkpoint.py", line 25, in load_checkpoint
    ckpt = torch.load(weights, map_location=map_location)  # load
  File "C:\Users\lllstandout\.conda\envs\yolov8\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\lllstandout\.conda\envs\yolov8\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "C:\Users\lllstandout\.conda\envs\yolov8\lib\site-packages\torch\serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'SimConv' on <module 'yolov6.layers.common' from 'G:\\Item_done\\yolo\\yolo5\\yolov6\\YOLOv6-yolov6-face\\yolov6\\layers\\common.py'>

**Comment by Chilicyy** [comment]
您好 @xinsuinizhuan 报错是因为模型和代码版本不一致导致的，新版代码对应的模型权重文件可以在[这个页面](https://github.com/meituan/YOLOv6/releases/tag/0.4.0)下载。
